package its.mnr.mp5.model;

import its.mnr.mp5.baseclass.ExtendedApplicationModuleImpl;
import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;
import its.mnr.mp5.model.common.AssetDataControl;
import its.mnr.mp5.vo.admin.MrlrefCustattribsViewImpl;
import its.mnr.mp5.vo.admin.MrltCustattribvaluesViewImpl;

import its.mnr.mp5.vo.admin.MrltCustattribvaluesViewRowImpl;
import its.mnr.mp5.vo.asset.AssetReadingImpl;
import its.mnr.mp5.vo.asset.MrltAssetViewImpl;
import its.mnr.mp5.vo.asset.MrltAssetViewRowImpl;

import its.mnr.mp5.vo.workorder.WOEventsImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewLinkImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 10:46:06 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetDataControlImpl extends ExtendedApplicationModuleImpl implements AssetDataControl {
    /**
     * This is the default constructor (do not remove).
     */
    public AssetDataControlImpl() {
    }
    public Boolean createAssetCustAttributes(){
//        System.out.println("createAssetCustAttributes()");
        
//        Integer x = 1;
        Boolean ret = false;
        RowIterator ritValues = getMrltCustattribvaluesView();
        MrltAssetViewImpl assetRow = (MrltAssetViewImpl) getMrltAssetView();
        
        String sAssetCd = (String)assetRow.getCurrentRow().getAttribute("Assetcd");
        String sAssetOrg = (String)assetRow.getCurrentRow().getAttribute("Org");
//        System.out.println("Asset: " + sAssetCd);
//        System.out.println("Org: " + sAssetOrg);
        
        RowSetIterator iter = this.getMrlrefCustattribsAsset().createRowSetIterator(null);
        iter.reset();

        while (iter.hasNext()) {
//            System.out.println("Int: " + x);
//            x= x+1;
            Row rw = iter.next();
            String sCustAttribCd = (String)rw.getAttribute("Attribcd");
//            System.out.println("Custom Attribute: " + sCustAttribCd);
//            System.out.println("Description: " +  (String)rw.getAttribute("Attribdesc"));
            
            MrltCustattribvaluesViewRowImpl rowImpl = (MrltCustattribvaluesViewRowImpl)ritValues.createRow();
            ritValues.insertRow(rowImpl);
            
            rowImpl.setOrg(sAssetOrg);
            rowImpl.setCustattribitem(sAssetCd);
            rowImpl.setCustattribcd(sCustAttribCd);
            ret = true;
        }
        iter.closeRowSetIterator();
        return ret;
    }
    
    /**
     * Container's getter for MrltAssetView.
     * @return MrltAssetView
     */
    public ExtendedViewObjectImpl getMrltAssetView() {
        return (ExtendedViewObjectImpl)findViewObject("MrltAssetView");
    }

    /**
     * Container's getter for MrltCustattribvaluesView.
     * @return MrltCustattribvaluesView
     */
    public MrltCustattribvaluesViewImpl getMrltCustattribvaluesView() {
        return (MrltCustattribvaluesViewImpl)findViewObject("MrltCustattribvaluesView");
    }

    /**
     * Container's getter for MrltReadingView.
     * @return MrltReadingView
     */
    public ExtendedViewObjectImpl getMrltReadingView() {
        return (ExtendedViewObjectImpl)findViewObject("MrltReadingView");
    }

    /**
     * Container's getter for MrltSparesView.
     * @return MrltSparesView
     */
    public ExtendedViewObjectImpl getMrltSparesView() {
        return (ExtendedViewObjectImpl)findViewObject("MrltSparesView");
    }

    /**
     * Container's getter for AssetCommentsView.
     * @return AssetCommentsView
     */
    public ExtendedViewObjectImpl getAssetCommentsView() {
        return (ExtendedViewObjectImpl)findViewObject("AssetCommentsView");
    }

    /**
     * Container's getter for MrltDocumentsView.
     * @return MrltDocumentsView
     */
    public ExtendedViewObjectImpl getMrltDocumentsView() {
        return (ExtendedViewObjectImpl)findViewObject("MrltDocumentsView");
    }

    /**
     * Container's getter for AssetCustAttribValuesLink1.
     * @return AssetCustAttribValuesLink1
     */
    public ViewLinkImpl getAssetCustAttribValuesLink1() {
        return (ViewLinkImpl)findViewLink("AssetCustAttribValuesLink1");
    }

    /**
     * Container's getter for AssetMrltReadingLink1.
     * @return AssetMrltReadingLink1
     */
    public ViewLinkImpl getAssetMrltReadingLink1() {
        return (ViewLinkImpl)findViewLink("AssetMrltReadingLink1");
    }

    /**
     * Container's getter for AssetSparesLink1.
     * @return AssetSparesLink1
     */
    public ViewLinkImpl getAssetSparesLink1() {
        return (ViewLinkImpl)findViewLink("AssetSparesLink1");
    }

    /**
     * Container's getter for AssetCommentsLink1.
     * @return AssetCommentsLink1
     */
    public ViewLinkImpl getAssetCommentsLink1() {
        return (ViewLinkImpl)findViewLink("AssetCommentsLink1");
    }

    /**
     * Container's getter for MrlrefCustattribsView1.
     * @return MrlrefCustattribsView1
     */
    public MrlrefCustattribsViewImpl getMrlrefCustattribsAsset() {
        return (MrlrefCustattribsViewImpl)findViewObject("MrlrefCustattribsAsset");
    }

    /**
     * Container's getter for HistoryWorkOrers.
     * @return HistoryWorkOrers
     */
    public WOEventsImpl getHistoryWorkOrers() {
        return (WOEventsImpl)findViewObject("HistoryWorkOrers");
    }

    /**
     * Container's getter for AssetWOEventLink1.
     * @return AssetWOEventLink1
     */
    public ViewLinkImpl getAssetWOEventLink1() {
        return (ViewLinkImpl)findViewLink("AssetWOEventLink1");
    }

    /**
     * Container's getter for MrltAssetdocumentsView.
     * @return MrltAssetdocumentsView
     */
    public ExtendedViewObjectImpl getMrltAssetdocumentsView() {
        return (ExtendedViewObjectImpl)findViewObject("MrltAssetdocumentsView");
    }

    /**
     * Container's getter for MrltAssetdocumentsFk1Link1.
     * @return MrltAssetdocumentsFk1Link1
     */
    public ViewLinkImpl getMrltAssetdocumentsFk1Link1() {
        return (ViewLinkImpl)findViewLink("MrltAssetdocumentsFk1Link1");
    }


    /**
     * Container's getter for AssetReading.
     * @return AssetReading
     */
    public ExtendedViewObjectImpl getAssetReading() {
        return (ExtendedViewObjectImpl)findViewObject("AssetReading");
    }

    /**
     * Container's getter for MrltAssetdocsQuery.
     * @return MrltAssetdocsQuery
     */
    public ExtendedViewObjectImpl getMrltAssetdocsQuery() {
        return (ExtendedViewObjectImpl)findViewObject("MrltAssetdocsQuery");
    }

    /**
     * Container's getter for AssetsAssetsDocViewLink1.
     * @return AssetsAssetsDocViewLink1
     */
    public ViewLinkImpl getAssetsAssetsDocViewLink1() {
        return (ViewLinkImpl)findViewLink("AssetsAssetsDocViewLink1");
    }

    /**
     * Container's getter for AssetWOTotalsView.
     * @return AssetWOTotalsView
     */
    public ExtendedViewObjectImpl getAssetWOTotalsView() {
        return (ExtendedViewObjectImpl)findViewObject("AssetWOTotalsView");
    }

    /**
     * Container's getter for AssetsWOTotalLink1.
     * @return AssetsWOTotalLink1
     */
    public ViewLinkImpl getAssetsWOTotalLink1() {
        return (ViewLinkImpl)findViewLink("AssetsWOTotalLink1");
    }

    /**
     * Container's getter for LastReadingType.
     * @return LastReadingType
     */
    public ExtendedViewObjectImpl getLastReadingType() {
        return (ExtendedViewObjectImpl)findViewObject("LastReadingType");
    }
}
