package its.mnr.mp5.vo.workorder;

import its.mnr.mp5.baseclass.ExtendedEntityImpl;
import its.mnr.mp5.baseclass.ExtendedViewRowImpl;
import its.mnr.mp5.model.Util;

import java.math.BigDecimal;

import java.util.Calendar;

import oracle.adf.share.ADFContext;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 21 17:41:16 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EstimateRowImpl extends ExtendedViewRowImpl {


    public static final int ENTITY_MRLTESTIMATE = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Estid {
            public Object get(EstimateRowImpl obj) {
                return obj.getEstid();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setEstid((Number)value);
            }
        }
        ,
        Wonum {
            public Object get(EstimateRowImpl obj) {
                return obj.getWonum();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setWonum((String)value);
            }
        }
        ,
        Ver {
            public Object get(EstimateRowImpl obj) {
                return obj.getVer();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setVer((String)value);
            }
        }
        ,
        Estdt {
            public Object get(EstimateRowImpl obj) {
                return obj.getEstdt();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setEstdt((Timestamp)value);
            }
        }
        ,
        Status {
            public Object get(EstimateRowImpl obj) {
                return obj.getStatus();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        }
        ,
        Updby {
            public Object get(EstimateRowImpl obj) {
                return obj.getUpdby();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setUpdby((String)value);
            }
        }
        ,
        Appnum {
            public Object get(EstimateRowImpl obj) {
                return obj.getAppnum();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setAppnum((String)value);
            }
        }
        ,
        Upddt {
            public Object get(EstimateRowImpl obj) {
                return obj.getUpddt();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setUpddt((Timestamp)value);
            }
        }
        ,
        Reason {
            public Object get(EstimateRowImpl obj) {
                return obj.getReason();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setReason((String)value);
            }
        }
        ,
        Equipnum {
            public Object get(EstimateRowImpl obj) {
                return obj.getEquipnum();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setEquipnum((String)value);
            }
        }
        ,
        Acctnum {
            public Object get(EstimateRowImpl obj) {
                return obj.getAcctnum();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setAcctnum((String)value);
            }
        }
        ,
        Hdrcd {
            public Object get(EstimateRowImpl obj) {
                return obj.getHdrcd();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setHdrcd((String)value);
            }
        }
        ,
        Tlbrhrs {
            public Object get(EstimateRowImpl obj) {
                return obj.getTlbrhrs();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setTlbrhrs((BigDecimal)value);
            }
        }
        ,
        Tlbrcst {
            public Object get(EstimateRowImpl obj) {
                return obj.getTlbrcst();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setTlbrcst((BigDecimal)value);
            }
        }
        ,
        Tpartcst {
            public Object get(EstimateRowImpl obj) {
                return obj.getTpartcst();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setTpartcst((BigDecimal)value);
            }
        }
        ,
        Ip {
            public Object get(EstimateRowImpl obj) {
                return obj.getIp();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setIp((String)value);
            }
        }
        ,
        Rsptype {
            public Object get(EstimateRowImpl obj) {
                return obj.getRsptype();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setRsptype((String)value);
            }
        }
        ,
        Eqtype {
            public Object get(EstimateRowImpl obj) {
                return obj.getEqtype();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setEqtype((String)value);
            }
        }
        ,
        Locode {
            public Object get(EstimateRowImpl obj) {
                return obj.getLocode();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setLocode((String)value);
            }
        }
        ,
        EstimateTask {
            public Object get(EstimateRowImpl obj) {
                return obj.getEstimateTask();
            }

            public void put(EstimateRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EstimateRowImpl object);

        public abstract void put(EstimateRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ESTID = AttributesEnum.Estid.index();
    public static final int WONUM = AttributesEnum.Wonum.index();
    public static final int VER = AttributesEnum.Ver.index();
    public static final int ESTDT = AttributesEnum.Estdt.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int UPDBY = AttributesEnum.Updby.index();
    public static final int APPNUM = AttributesEnum.Appnum.index();
    public static final int UPDDT = AttributesEnum.Upddt.index();
    public static final int REASON = AttributesEnum.Reason.index();
    public static final int EQUIPNUM = AttributesEnum.Equipnum.index();
    public static final int ACCTNUM = AttributesEnum.Acctnum.index();
    public static final int HDRCD = AttributesEnum.Hdrcd.index();
    public static final int TLBRHRS = AttributesEnum.Tlbrhrs.index();
    public static final int TLBRCST = AttributesEnum.Tlbrcst.index();
    public static final int TPARTCST = AttributesEnum.Tpartcst.index();
    public static final int IP = AttributesEnum.Ip.index();
    public static final int RSPTYPE = AttributesEnum.Rsptype.index();
    public static final int EQTYPE = AttributesEnum.Eqtype.index();
    public static final int LOCODE = AttributesEnum.Locode.index();
    public static final int ESTIMATETASK = AttributesEnum.EstimateTask.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EstimateRowImpl() {
    }

    /**
     * Gets MrltEstimate entity object.
     * @return the MrltEstimate
     */
    public ExtendedEntityImpl getMrltEstimate() {
        return (ExtendedEntityImpl)getEntity(ENTITY_MRLTESTIMATE);
    }

    /**
     * Gets the attribute value for ESTID using the alias name Estid.
     * @return the ESTID
     */
    public Number getEstid() {
        return (Number) getAttributeInternal(ESTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTID using the alias name Estid.
     * @param value value to set the ESTID
     */
    public void setEstid(Number value) {
        setAttributeInternal(ESTID, value);
    }

    /**
     * Gets the attribute value for WONUM using the alias name Wonum.
     * @return the WONUM
     */
    public String getWonum() {
        return (String) getAttributeInternal(WONUM);
    }

    /**
     * Sets <code>value</code> as attribute value for WONUM using the alias name Wonum.
     * @param value value to set the WONUM
     */
    public void setWonum(String value) {
        setAttributeInternal(WONUM, value);
    }

    /**
     * Gets the attribute value for VER using the alias name Ver.
     * @return the VER
     */
    public String getVer() {
        return (String) getAttributeInternal(VER);
    }

    /**
     * Sets <code>value</code> as attribute value for VER using the alias name Ver.
     * @param value value to set the VER
     */
    public void setVer(String value) {
        setAttributeInternal(VER, value);
    }

    /**
     * Gets the attribute value for ESTDT using the alias name Estdt.
     * @return the ESTDT
     */
    public Timestamp getEstdt() {
        return (Timestamp) getAttributeInternal(ESTDT);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTDT using the alias name Estdt.
     * @param value value to set the ESTDT
     */
    public void setEstdt(Timestamp value) {
        setAttributeInternal(ESTDT, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for UPDBY using the alias name Updby.
     * @return the UPDBY
     */
    public String getUpdby() {
        return (String) getAttributeInternal(UPDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDBY using the alias name Updby.
     * @param value value to set the UPDBY
     */
    public void setUpdby(String value) {
        setAttributeInternal(UPDBY, value);
    }

    /**
     * Gets the attribute value for APPNUM using the alias name Appnum.
     * @return the APPNUM
     */
    public String getAppnum() {
        return (String) getAttributeInternal(APPNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for APPNUM using the alias name Appnum.
     * @param value value to set the APPNUM
     */
    public void setAppnum(String value) {
        setAttributeInternal(APPNUM, value);
    }

    /**
     * Gets the attribute value for UPDDT using the alias name Upddt.
     * @return the UPDDT
     */
    public Timestamp getUpddt() {
        return (Timestamp) getAttributeInternal(UPDDT);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDDT using the alias name Upddt.
     * @param value value to set the UPDDT
     */
    public void setUpddt(Timestamp value) {
        setAttributeInternal(UPDDT, value);
    }

    /**
     * Gets the attribute value for REASON using the alias name Reason.
     * @return the REASON
     */
    public String getReason() {
        return (String) getAttributeInternal(REASON);
    }

    /**
     * Sets <code>value</code> as attribute value for REASON using the alias name Reason.
     * @param value value to set the REASON
     */
    public void setReason(String value) {
        setAttributeInternal(REASON, value);
    }

    /**
     * Gets the attribute value for EQUIPNUM using the alias name Equipnum.
     * @return the EQUIPNUM
     */
    public String getEquipnum() {
        return (String) getAttributeInternal(EQUIPNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for EQUIPNUM using the alias name Equipnum.
     * @param value value to set the EQUIPNUM
     */
    public void setEquipnum(String value) {
        setAttributeInternal(EQUIPNUM, value);
    }

    /**
     * Gets the attribute value for ACCTNUM using the alias name Acctnum.
     * @return the ACCTNUM
     */
    public String getAcctnum() {
        return (String) getAttributeInternal(ACCTNUM);
    }

    /**
     * Sets <code>value</code> as attribute value for ACCTNUM using the alias name Acctnum.
     * @param value value to set the ACCTNUM
     */
    public void setAcctnum(String value) {
        setAttributeInternal(ACCTNUM, value);
    }

    /**
     * Gets the attribute value for HDRCD using the alias name Hdrcd.
     * @return the HDRCD
     */
    public String getHdrcd() {
        return (String) getAttributeInternal(HDRCD);
    }

    /**
     * Sets <code>value</code> as attribute value for HDRCD using the alias name Hdrcd.
     * @param value value to set the HDRCD
     */
    public void setHdrcd(String value) {
        setAttributeInternal(HDRCD, value);
    }

    /**
     * Gets the attribute value for TLBRHRS using the alias name Tlbrhrs.
     * @return the TLBRHRS
     */
    public BigDecimal getTlbrhrs() {
        return (BigDecimal) getAttributeInternal(TLBRHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for TLBRHRS using the alias name Tlbrhrs.
     * @param value value to set the TLBRHRS
     */
    public void setTlbrhrs(BigDecimal value) {
        setAttributeInternal(TLBRHRS, value);
    }

    /**
     * Gets the attribute value for TLBRCST using the alias name Tlbrcst.
     * @return the TLBRCST
     */
    public BigDecimal getTlbrcst() {
        return (BigDecimal) getAttributeInternal(TLBRCST);
    }

    /**
     * Sets <code>value</code> as attribute value for TLBRCST using the alias name Tlbrcst.
     * @param value value to set the TLBRCST
     */
    public void setTlbrcst(BigDecimal value) {
        setAttributeInternal(TLBRCST, value);
    }

    /**
     * Gets the attribute value for TPARTCST using the alias name Tpartcst.
     * @return the TPARTCST
     */
    public BigDecimal getTpartcst() {
        return (BigDecimal) getAttributeInternal(TPARTCST);
    }

    /**
     * Sets <code>value</code> as attribute value for TPARTCST using the alias name Tpartcst.
     * @param value value to set the TPARTCST
     */
    public void setTpartcst(BigDecimal value) {
        setAttributeInternal(TPARTCST, value);
    }

    /**
     * Gets the attribute value for IP using the alias name Ip.
     * @return the IP
     */
    public String getIp() {
        return (String) getAttributeInternal(IP);
    }

    /**
     * Sets <code>value</code> as attribute value for IP using the alias name Ip.
     * @param value value to set the IP
     */
    public void setIp(String value) {
        setAttributeInternal(IP, value);
    }

    /**
     * Gets the attribute value for RSPTYPE using the alias name Rsptype.
     * @return the RSPTYPE
     */
    public String getRsptype() {
        return (String) getAttributeInternal(RSPTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for RSPTYPE using the alias name Rsptype.
     * @param value value to set the RSPTYPE
     */
    public void setRsptype(String value) {
        setAttributeInternal(RSPTYPE, value);
    }

    /**
     * Gets the attribute value for EQTYPE using the alias name Eqtype.
     * @return the EQTYPE
     */
    public String getEqtype() {
        return (String) getAttributeInternal(EQTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for EQTYPE using the alias name Eqtype.
     * @param value value to set the EQTYPE
     */
    public void setEqtype(String value) {
        setAttributeInternal(EQTYPE, value);
    }

    /**
     * Gets the attribute value for LOCODE using the alias name Locode.
     * @return the LOCODE
     */
    public String getLocode() {
        return (String) getAttributeInternal(LOCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCODE using the alias name Locode.
     * @param value value to set the LOCODE
     */
    public void setLocode(String value) {
        setAttributeInternal(LOCODE, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EstimateTask.
     */
    public RowIterator getEstimateTask() {
        return (RowIterator)getAttributeInternal(ESTIMATETASK);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
