package its.mnr.mp5.vo.workorder;

import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 05 09:54:27 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LaborCostImpl extends ExtendedViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LaborCostImpl() {
    }

    /**
     * Returns the variable value for ARTaskIdBind.
     * @return variable value for ARTaskIdBind
     */
    public String getARTaskIdBind() {
        return (String)ensureVariableManager().getVariableValue("ARTaskIdBind");
    }

    /**
     * Sets <code>value</code> for variable ARTaskIdBind.
     * @param value value to bind as ARTaskIdBind
     */
    public void setARTaskIdBind(String value) {
        ensureVariableManager().setVariableValue("ARTaskIdBind", value);
    }

    /**
     * Returns the variable value for ShiftCdBind.
     * @return variable value for ShiftCdBind
     */
    public String getShiftCdBind() {
        return (String)ensureVariableManager().getVariableValue("ShiftCdBind");
    }

    /**
     * Sets <code>value</code> for variable ShiftCdBind.
     * @param value value to bind as ShiftCdBind
     */
    public void setShiftCdBind(String value) {
        ensureVariableManager().setVariableValue("ShiftCdBind", value);
    }

    /**
     * Returns the variable value for ARateIdBind.
     * @return variable value for ARateIdBind
     */
    public String getARateIdBind() {
        return (String)ensureVariableManager().getVariableValue("ARateIdBind");
    }

    /**
     * Sets <code>value</code> for variable ARateIdBind.
     * @param value value to bind as ARateIdBind
     */
    public void setARateIdBind(String value) {
        ensureVariableManager().setVariableValue("ARateIdBind", value);
    }

    /**
     * Returns the variable value for TaskIdBind.
     * @return variable value for TaskIdBind
     */
    public String getTaskIdBind() {
        return (String)ensureVariableManager().getVariableValue("TaskIdBind");
    }

    /**
     * Sets <code>value</code> for variable TaskIdBind.
     * @param value value to bind as TaskIdBind
     */
    public void setTaskIdBind(String value) {
        ensureVariableManager().setVariableValue("TaskIdBind", value);
    }
}
