package its.mnr.mp5.vo.workorder;

import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 19 15:45:04 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TaskLocationImpl extends ExtendedViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TaskLocationImpl() {
    }

    /**
     * Returns the bind variable value for TaskIdBind.
     * @return bind variable value for TaskIdBind
     */
    public String getTaskIdBind() {
        return (String)getNamedWhereClauseParam("TaskIdBind");
    }

    /**
     * Sets <code>value</code> for bind variable TaskIdBind.
     * @param value value to bind as TaskIdBind
     */
    public void setTaskIdBind(String value) {
        setNamedWhereClauseParam("TaskIdBind", value);
    }
}
