package its.mnr.mp5.vo.admin;

import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 10:30:04 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MrltCustattribvaluesViewImpl extends ExtendedViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MrltCustattribvaluesViewImpl() {
    }

    
}
