package its.mnr.mp5.vo.invoice.client;

import its.mnr.mp5.vo.invoice.common.InvoiceAssemblyResultsRow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 07 15:52:47 PST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceAssemblyResultsRowClient extends RowImpl implements InvoiceAssemblyResultsRow {
    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceAssemblyResultsRowClient() {
    }


    public oracle.jbo.domain.Number createInvoiceHeader() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "createInvoiceHeader", null, null);
        return (oracle.jbo.domain.Number) _ret;
    }

    public boolean createInvoiceItem(oracle.jbo.domain.Number pHeaderId, String pWO, String pEquip, String pVer,
                                     Double pLabor, Double pPart, Double pTax, Double pTotal, Date pCompdt,
                                     Date pStartdt, String pHdrCode) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "createInvoiceItem", new String[] {
                                                                         "oracle.jbo.domain.Number", "java.lang.String",
                                                                         "java.lang.String", "java.lang.String",
                                                                         "java.lang.Double", "java.lang.Double",
                                                                         "java.lang.Double", "java.lang.Double",
                                                                         "oracle.jbo.domain.Date",
                                                                         "oracle.jbo.domain.Date", "java.lang.String"
        }, new Object[] { pHeaderId, pWO, pEquip, pVer, pLabor, pPart, pTax, pTotal, pCompdt, pStartdt, pHdrCode });
        return ((Boolean) _ret).booleanValue();
    }

    public oracle.jbo.domain.Number getInvoiceNum(oracle.jbo.domain.Number pHeaderId) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "getInvoiceNum", new String[] {
                                                                         "oracle.jbo.domain.Number" }, new Object[] {
                                                                         pHeaderId });
        return (oracle.jbo.domain.Number) _ret;
    }

    public Boolean updateWORFI(String pevtcode) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "updateWORFI", new String[] {
                                                                         "java.lang.String" }, new Object[] {
                                                                         pevtcode });
        return (Boolean) _ret;
    }
}
