package its.mnr.mp5.vo.invoice.client;

import its.mnr.mp5.vo.invoice.common.MrltInvoiceheaderViewRow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 08 14:07:18 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MrltInvoiceheaderViewRowClient extends RowImpl implements MrltInvoiceheaderViewRow {
    /**
     * This is the default constructor (do not remove).
     */
    public MrltInvoiceheaderViewRowClient() {
    }


    public String WorkOrderRFIUpd(oracle.jbo.domain.Number pInvHdrId, String pNewStatus) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "WorkOrderRFIUpd", new String[] {
                                                                         "oracle.jbo.domain.Number", "java.lang.String"
        }, new Object[] { pInvHdrId, pNewStatus });
        return (String) _ret;
    }

    public Boolean deleteInvoiceXMLFile(oracle.jbo.domain.Number pInvNum, String pType) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "deleteInvoiceXMLFile", new String[] {
                                                                         "oracle.jbo.domain.Number", "java.lang.String"
        }, new Object[] { pInvNum, pType });
        return (Boolean) _ret;
    }

    public boolean updateInvoiceStatus(oracle.jbo.domain.Number pInvNum, String newStatus) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "updateInvoiceStatus", new String[] {
                                                                         "oracle.jbo.domain.Number", "java.lang.String"
        }, new Object[] { pInvNum, newStatus });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean writeInvoiceCrXML(oracle.jbo.domain.Number pInvNum) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "writeInvoiceCrXML", new String[] {
                                                                         "oracle.jbo.domain.Number" }, new Object[] {
                                                                         pInvNum });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean writeInvoiceEstXML(oracle.jbo.domain.Number pInvNum) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "writeInvoiceEstXML", new String[] {
                                                                         "oracle.jbo.domain.Number" }, new Object[] {
                                                                         pInvNum });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean writeInvoiceRtroXML(oracle.jbo.domain.Number pInvNum) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "writeInvoiceRtroXML", new String[] {
                                                                         "oracle.jbo.domain.Number" }, new Object[] {
                                                                         pInvNum });
        return ((Boolean) _ret).booleanValue();
    }

    public boolean writeInvoiceStdXML(oracle.jbo.domain.Number pInvNum) {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "writeInvoiceStdXML", new String[] {
                                                                         "oracle.jbo.domain.Number" }, new Object[] {
                                                                         pInvNum });
        return ((Boolean) _ret).booleanValue();
    }
}
