package its.mnr.mp5.model.common;

import java.util.ArrayList;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 20 10:53:07 PST 2014
// ---------------------------------------------------------------------
public interface CCDataControl extends ApplicationModule {

    void initCycleCountParts();

    boolean createCCList(Integer iListId, String sTrans, String sStoreroom);

    Integer executeCycleCountParts(Integer sListid);

    boolean createCCPartStores(Integer iListId, ArrayList<String> sStoreroom);
}
