package its.mnr.mp5.vo.parts.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 14 09:38:34 PST 2017
// ---------------------------------------------------------------------
public interface PartsMaintViewRow extends Row {
    String getParCode();

    void setParCode(String value);

    String getParClassOrg();

    void setParClassOrg(String value);

    String getParClass();

    void setParClass(String value);

    Double getParBaseprice();

    void setParBaseprice(Double value);

    Double getParAvgprice();


    String getParBuyer();

    void setParBuyer(String value);

    Timestamp getParCreated();

    void setParCreated(Timestamp value);

    String getParCreatedby();

    void setParCreatedby(String value);

    String getParDesc();

    void setParDesc(String value);

    Double getParLastprice();


    String getParNotused();

    void setParNotused(String value);

    String getParOrg();

    void setParOrg(String value);

    String getParPrefsup();

    void setParPrefsup(String value);

    String getParPrefsupOrg();

    void setParPrefsupOrg(String value);

    Double getParPrefsupprice();

    void setParPrefsupprice(Double value);

    String getParPrefuom();

    void setParPrefuom(String value);

    Double getParStdprice();

    void setParStdprice(Double value);

    String getParTax();

    void setParTax(String value);

    String getParUom();

    void setParUom(String value);

    Timestamp getParUpdated();

    void setParUpdated(Timestamp value);

    String getParUpdatedby();

    void setParUpdatedby(String value);

    String gettClassSwitcher();

    void settClassSwitcher(String value);

    String getItsGl();

    void setItsGl(String value);

    String getItsCyclecnt();

    void setItsCyclecnt(String value);

    String gettPrefSup();

    void settPrefSup(String value);

    String gettParCode();

    void settParCode(String value);

    Double gettTotalStoQty();

    void settTotalStoQty(Double value);

    String gettPostedParNotused();

    void settPostedParNotused(String value);

    void writePartCSV();
}

