package its.mnr.mp5.vo.invoice.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 07 15:52:45 PST 2014
// ---------------------------------------------------------------------
public interface InvoiceAssemblyResultsRow extends Row {
    oracle.jbo.domain.Number createInvoiceHeader();

    boolean createInvoiceItem(oracle.jbo.domain.Number pHeaderId, String pWO, String pEquip, String pVer, Double pLabor,
                              Double pPart, Double pTax, Double pTotal, Date pCompdt, Date pStartdt, String pHdrCode);

    Boolean updateWORFI(String pevtcode);

    oracle.jbo.domain.Number getInvoiceNum(oracle.jbo.domain.Number pHeaderId);
}
