package its.mnr.mp5.vo.cyclecount.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 17 16:03:38 PDT 2014
// ---------------------------------------------------------------------
public interface CycleCountPartsMainRow extends Row {
    String writeCCStoreListXML(String pList, String pType);

    String CCPROCESSLISTXML(String PLISTID, String PTYPE, String PFILE);
}
