package its.mnr.mp5.vo.cyclecount;

import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;

import java.sql.ResultSet;

import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Dec 21 10:46:37 PST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CycleCountPartsMain_distBinViewImpl
  extends ExtendedViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  public CycleCountPartsMain_distBinViewImpl()
  {
  }

  /**
   * Returns the variable value for bListid.
   * @return variable value for bListid
   */
  public Integer getbListid()
  {
    return (Integer) ensureVariableManager().getVariableValue("bListid");
  }

  /**
   * Sets <code>value</code> for variable bListid.
   * @param value value to bind as bListid
   */
  public void setbListid(Integer value)
  {
    ensureVariableManager().setVariableValue("bListid", value);
  }

  /**
   * executeQueryForCollection - overridden for custom java data source support.
   */
  protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams)
  {
    super.executeQueryForCollection(qc, params, noUserParams);
  }

  /**
   * hasNextForCollection - overridden for custom java data source support.
   */
  protected boolean hasNextForCollection(Object qc)
  {
    boolean bRet = super.hasNextForCollection(qc);
    return bRet;
  }

  /**
   * createRowFromResultSet - overridden for custom java data source support.
   */
  protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet)
  {
    ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
    return value;
  }

  /**
   * getQueryHitCount - overridden for custom java data source support.
   */
  public long getQueryHitCount(ViewRowSetImpl viewRowSet)
  {
    long value = super.getQueryHitCount(viewRowSet);
    return value;
  }
}
