package its.mnr.mp5.vo.invoice;

import its.mnr.mp5.baseclass.ExtendedViewRowImpl;

import its.mnr.mp5.vo.invoice.common.InvoiceRetroResultsRow;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 24 14:30:49 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceRetroResultsRowImpl extends ExtendedViewRowImpl implements InvoiceRetroResultsRow {
    
    public Number createInvoiceHeader(){
        //System.out.println("inside InvoiceAssemblyResultsRowImpl:createInvoiceHeader()");
        Number pHeaderId;
        Double dLabor = this.getCreditDebitSum();
        Double dPart = new Double (0.0);
        Double pTax = new Double (0.0);
        Double pTotal = dLabor;
        String pAcctNum = this.getAcctnum();
        String pInt = "N";
        Double pInvCr = null;
        Number pRef = null;
        String pType = "RTRO";
                                                                                                           
        DBTransaction trans = getDBTransaction();
        pHeaderId = getValueFromSequence("MRLTINVHEADERSEQ", trans); 
        
        RowSet rs = this.getMrltInvoiceheaderView();
        MrltInvoiceheaderViewImpl invHeaderImpl = (MrltInvoiceheaderViewImpl)rs.getViewObject();
        
        Boolean chk = invHeaderImpl.createInvoiceHeader(pHeaderId, pType, dLabor, dPart, pTax, pTotal, pAcctNum, pInt, pInvCr, pRef);
            
        if(chk){
        return pHeaderId;
        }
        return null;
        }
    public Boolean createInvoiceRtroItem(Number pHeaderId, Number pInvoice, String pWO, Number pAct, String pOldVer,
                                         String pNewVer, String pOldARTaskId, String pNewARTaskId, Double pOldRate,
                                         Double pNewRate, String pShift, Double pHrs, String pOldRateType,
                                         String pNewRateType, String pEquip, String pTask, String pCompCd,
                                         String pDamCd, String pDamDesc, String pLocCd,
                                         String pLocDesc, String pRepCd, String pRepDesc, String pHdrCode){
        //System.out.println("inside InvoiceAssemblyResultsRowImpl:createInvoiceItem()");
        Boolean ret = false;                                                                                      
        DBTransaction trans = getDBTransaction();

        Number pItemId = getValueFromSequence("MRLTINVRTROITEMSEQ", trans); 
            
        RowSet rsItem = this.getMrltInvoicertroitemView();
        MrltInvoicertroitemViewImpl invItemImpl = (MrltInvoicertroitemViewImpl)rsItem.getViewObject();
        ret = invItemImpl.createInvoiceRtroItem(pItemId, pHeaderId, pInvoice, pWO, pAct, pOldVer, pNewVer, pOldARTaskId, pNewARTaskId,
                                  pOldRate, pNewRate, pShift, pHrs, pOldRateType, pNewRateType, pEquip, pTask, pCompCd,
                                  pDamCd, pDamDesc, pLocCd, pLocDesc, pRepCd, pRepDesc, pHdrCode);


        return ret;
        }
    
    public Number getInvoiceNum(Number pHeaderId) {
        //System.out.println("getInvoiceNum()");
        //set and execute View Criteria
        RowSet rs = this.getMrltInvoiceheaderView();
        MrltInvoiceheaderViewImpl invHeaderImpl = (MrltInvoiceheaderViewImpl)rs.getViewObject();
        ViewCriteria vc = invHeaderImpl.getViewCriteria("getInvoiceNumByHeaderId");
        vc.resetCriteria();
        invHeaderImpl.setInvHeaderIdBind(pHeaderId);
        invHeaderImpl.applyViewCriteria(vc);
        // set range size to 1 since we expect a single record
        invHeaderImpl.setRangeSize(1);
        // execute query to make sure we get latest data!
        invHeaderImpl.executeQuery();
        Row rw = invHeaderImpl.first();
        if (rw != null) {
            //System.out.println("getInvoiceNum Ret = " + (Number)rw.getAttribute("Invnum"));
            Number nInvNum = (Number)rw.getAttribute("Invnum");
            rs.closeRowSet();
            return nInvNum;
        }
        return null;
    }
    public static Number getValueFromSequence(String sequenceName, DBTransaction trans){
        SequenceImpl s = new SequenceImpl(sequenceName, trans);
        return s.getSequenceNumber();
        }
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Invnum {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getInvnum();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setInvnum((Number)value);
            }
        }
        ,
        Invdt {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getInvdt();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setInvdt((Date)value);
            }
        }
        ,
        Acctnum {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getAcctnum();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setAcctnum((String)value);
            }
        }
        ,
        Wo {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getWo();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setWo((String)value);
            }
        }
        ,
        Hdrcode {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getHdrcode();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setHdrcode((String)value);
            }
        }
        ,
        Activever {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getActivever();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setActivever((String)value);
            }
        }
        ,
        Startdt {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getStartdt();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setStartdt((Date)value);
            }
        }
        ,
        Completedt {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getCompletedt();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setCompletedt((Date)value);
            }
        }
        ,
        Contractver {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getContractver();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setContractver((String)value);
            }
        }
        ,
        Act {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getAct();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setAct((Number)value);
            }
        }
        ,
        Oldratetype {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getOldratetype();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setOldratetype((String)value);
            }
        }
        ,
        Shift {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getShift();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setShift((String)value);
            }
        }
        ,
        Hrs {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getHrs();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setHrs((Double)value);
            }
        }
        ,
        Oldrate {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getOldrate();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setOldrate((Double)value);
            }
        }
        ,
        ItsCompcode {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsCompcode();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsCompcode((String)value);
            }
        }
        ,
        ItsLoccode {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsLoccode();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsLoccode((String)value);
            }
        }
        ,
        ItsLocdesc {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsLocdesc();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsLocdesc((String)value);
            }
        }
        ,
        ItsDamcode {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsDamcode();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsDamcode((String)value);
            }
        }
        ,
        ItsDamdesc {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsDamdesc();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsDamdesc((String)value);
            }
        }
        ,
        ItsRepcode {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsRepcode();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsRepcode((String)value);
            }
        }
        ,
        ItsRepdesc {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsRepdesc();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsRepdesc((String)value);
            }
        }
        ,
        ItsTaskdesc {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getItsTaskdesc();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setItsTaskdesc((String)value);
            }
        }
        ,
        Oldartaskid {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getOldartaskid();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setOldartaskid((String)value);
            }
        }
        ,
        Newartaskid {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getNewartaskid();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setNewartaskid((String)value);
            }
        }
        ,
        Newratetype {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getNewratetype();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setNewratetype((String)value);
            }
        }
        ,
        Equipcharge {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getEquipcharge();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setEquipcharge((String)value);
            }
        }
        ,
        Newrate {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getNewrate();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setNewrate((Double)value);
            }
        }
        ,
        Rtroratetype {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getRtroratetype();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setRtroratetype((String)value);
            }
        }
        ,
        Rtrover {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getRtrover();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setRtrover((String)value);
            }
        }
        ,
        Rtronewartaskid {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getRtronewartaskid();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setRtronewartaskid((String)value);
            }
        }
        ,
        Rtrorate {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getRtrorate();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setRtrorate((Double)value);
            }
        }
        ,
        CreditDebit {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getCreditDebit();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setCreditDebit((Double)value);
            }
        }
        ,
        CreditDebitSum {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getCreditDebitSum();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setCreditDebitSum((Double)value);
            }
        }
        ,
        MrltInvoiceheaderView {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getMrltInvoiceheaderView();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MrltInvoicertroitemView {
            public Object get(InvoiceRetroResultsRowImpl obj) {
                return obj.getMrltInvoicertroitemView();
            }

            public void put(InvoiceRetroResultsRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(InvoiceRetroResultsRowImpl object);

        public abstract void put(InvoiceRetroResultsRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INVNUM = AttributesEnum.Invnum.index();
    public static final int INVDT = AttributesEnum.Invdt.index();
    public static final int ACCTNUM = AttributesEnum.Acctnum.index();
    public static final int WO = AttributesEnum.Wo.index();
    public static final int HDRCODE = AttributesEnum.Hdrcode.index();
    public static final int ACTIVEVER = AttributesEnum.Activever.index();
    public static final int STARTDT = AttributesEnum.Startdt.index();
    public static final int COMPLETEDT = AttributesEnum.Completedt.index();
    public static final int CONTRACTVER = AttributesEnum.Contractver.index();
    public static final int ACT = AttributesEnum.Act.index();
    public static final int OLDRATETYPE = AttributesEnum.Oldratetype.index();
    public static final int SHIFT = AttributesEnum.Shift.index();
    public static final int HRS = AttributesEnum.Hrs.index();
    public static final int OLDRATE = AttributesEnum.Oldrate.index();
    public static final int ITSCOMPCODE = AttributesEnum.ItsCompcode.index();
    public static final int ITSLOCCODE = AttributesEnum.ItsLoccode.index();
    public static final int ITSLOCDESC = AttributesEnum.ItsLocdesc.index();
    public static final int ITSDAMCODE = AttributesEnum.ItsDamcode.index();
    public static final int ITSDAMDESC = AttributesEnum.ItsDamdesc.index();
    public static final int ITSREPCODE = AttributesEnum.ItsRepcode.index();
    public static final int ITSREPDESC = AttributesEnum.ItsRepdesc.index();
    public static final int ITSTASKDESC = AttributesEnum.ItsTaskdesc.index();
    public static final int OLDARTASKID = AttributesEnum.Oldartaskid.index();
    public static final int NEWARTASKID = AttributesEnum.Newartaskid.index();
    public static final int NEWRATETYPE = AttributesEnum.Newratetype.index();
    public static final int EQUIPCHARGE = AttributesEnum.Equipcharge.index();
    public static final int NEWRATE = AttributesEnum.Newrate.index();
    public static final int RTRORATETYPE = AttributesEnum.Rtroratetype.index();
    public static final int RTROVER = AttributesEnum.Rtrover.index();
    public static final int RTRONEWARTASKID = AttributesEnum.Rtronewartaskid.index();
    public static final int RTRORATE = AttributesEnum.Rtrorate.index();
    public static final int CREDITDEBIT = AttributesEnum.CreditDebit.index();
    public static final int CREDITDEBITSUM = AttributesEnum.CreditDebitSum.index();
    public static final int MRLTINVOICEHEADERVIEW = AttributesEnum.MrltInvoiceheaderView.index();
    public static final int MRLTINVOICERTROITEMVIEW = AttributesEnum.MrltInvoicertroitemView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvoiceRetroResultsRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Invnum.
     * @return the Invnum
     */
    public Number getInvnum() {
        return (Number) getAttributeInternal(INVNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Invnum.
     * @param value value to set the  Invnum
     */
    public void setInvnum(Number value) {
        setAttributeInternal(INVNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Invdt.
     * @return the Invdt
     */
    public Date getInvdt() {
        return (Date) getAttributeInternal(INVDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Invdt.
     * @param value value to set the  Invdt
     */
    public void setInvdt(Date value) {
        setAttributeInternal(INVDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Acctnum.
     * @return the Acctnum
     */
    public String getAcctnum() {
        return (String) getAttributeInternal(ACCTNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Acctnum.
     * @param value value to set the  Acctnum
     */
    public void setAcctnum(String value) {
        setAttributeInternal(ACCTNUM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wo.
     * @return the Wo
     */
    public String getWo() {
        return (String) getAttributeInternal(WO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wo.
     * @param value value to set the  Wo
     */
    public void setWo(String value) {
        setAttributeInternal(WO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Hdrcode.
     * @return the Hdrcode
     */
    public String getHdrcode() {
        return (String) getAttributeInternal(HDRCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Hdrcode.
     * @param value value to set the  Hdrcode
     */
    public void setHdrcode(String value) {
        setAttributeInternal(HDRCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Activever.
     * @return the Activever
     */
    public String getActivever() {
        return (String) getAttributeInternal(ACTIVEVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Activever.
     * @param value value to set the  Activever
     */
    public void setActivever(String value) {
        setAttributeInternal(ACTIVEVER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Startdt.
     * @return the Startdt
     */
    public Date getStartdt() {
        return (Date) getAttributeInternal(STARTDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Startdt.
     * @param value value to set the  Startdt
     */
    public void setStartdt(Date value) {
        setAttributeInternal(STARTDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Completedt.
     * @return the Completedt
     */
    public Date getCompletedt() {
        return (Date) getAttributeInternal(COMPLETEDT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Completedt.
     * @param value value to set the  Completedt
     */
    public void setCompletedt(Date value) {
        setAttributeInternal(COMPLETEDT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Contractver.
     * @return the Contractver
     */
    public String getContractver() {
        return (String) getAttributeInternal(CONTRACTVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Contractver.
     * @param value value to set the  Contractver
     */
    public void setContractver(String value) {
        setAttributeInternal(CONTRACTVER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Act.
     * @return the Act
     */
    public Number getAct() {
        return (Number) getAttributeInternal(ACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Act.
     * @param value value to set the  Act
     */
    public void setAct(Number value) {
        setAttributeInternal(ACT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Oldratetype.
     * @return the Oldratetype
     */
    public String getOldratetype() {
        return (String) getAttributeInternal(OLDRATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Oldratetype.
     * @param value value to set the  Oldratetype
     */
    public void setOldratetype(String value) {
        setAttributeInternal(OLDRATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Shift.
     * @return the Shift
     */
    public String getShift() {
        return (String) getAttributeInternal(SHIFT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Shift.
     * @param value value to set the  Shift
     */
    public void setShift(String value) {
        setAttributeInternal(SHIFT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Hrs.
     * @return the Hrs
     */
    public Double getHrs() {
        return (Double) getAttributeInternal(HRS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Hrs.
     * @param value value to set the  Hrs
     */
    public void setHrs(Double value) {
        setAttributeInternal(HRS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Oldrate.
     * @return the Oldrate
     */
    public Double getOldrate() {
        return (Double) getAttributeInternal(OLDRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Oldrate.
     * @param value value to set the  Oldrate
     */
    public void setOldrate(Double value) {
        setAttributeInternal(OLDRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsCompcode.
     * @return the ItsCompcode
     */
    public String getItsCompcode() {
        return (String) getAttributeInternal(ITSCOMPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsCompcode.
     * @param value value to set the  ItsCompcode
     */
    public void setItsCompcode(String value) {
        setAttributeInternal(ITSCOMPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsLoccode.
     * @return the ItsLoccode
     */
    public String getItsLoccode() {
        return (String) getAttributeInternal(ITSLOCCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsLoccode.
     * @param value value to set the  ItsLoccode
     */
    public void setItsLoccode(String value) {
        setAttributeInternal(ITSLOCCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsLocdesc.
     * @return the ItsLocdesc
     */
    public String getItsLocdesc() {
        return (String) getAttributeInternal(ITSLOCDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsLocdesc.
     * @param value value to set the  ItsLocdesc
     */
    public void setItsLocdesc(String value) {
        setAttributeInternal(ITSLOCDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsDamcode.
     * @return the ItsDamcode
     */
    public String getItsDamcode() {
        return (String) getAttributeInternal(ITSDAMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsDamcode.
     * @param value value to set the  ItsDamcode
     */
    public void setItsDamcode(String value) {
        setAttributeInternal(ITSDAMCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsDamdesc.
     * @return the ItsDamdesc
     */
    public String getItsDamdesc() {
        return (String) getAttributeInternal(ITSDAMDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsDamdesc.
     * @param value value to set the  ItsDamdesc
     */
    public void setItsDamdesc(String value) {
        setAttributeInternal(ITSDAMDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsRepcode.
     * @return the ItsRepcode
     */
    public String getItsRepcode() {
        return (String) getAttributeInternal(ITSREPCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsRepcode.
     * @param value value to set the  ItsRepcode
     */
    public void setItsRepcode(String value) {
        setAttributeInternal(ITSREPCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsRepdesc.
     * @return the ItsRepdesc
     */
    public String getItsRepdesc() {
        return (String) getAttributeInternal(ITSREPDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsRepdesc.
     * @param value value to set the  ItsRepdesc
     */
    public void setItsRepdesc(String value) {
        setAttributeInternal(ITSREPDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItsTaskdesc.
     * @return the ItsTaskdesc
     */
    public String getItsTaskdesc() {
        return (String) getAttributeInternal(ITSTASKDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItsTaskdesc.
     * @param value value to set the  ItsTaskdesc
     */
    public void setItsTaskdesc(String value) {
        setAttributeInternal(ITSTASKDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Oldartaskid.
     * @return the Oldartaskid
     */
    public String getOldartaskid() {
        return (String) getAttributeInternal(OLDARTASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Oldartaskid.
     * @param value value to set the  Oldartaskid
     */
    public void setOldartaskid(String value) {
        setAttributeInternal(OLDARTASKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Newartaskid.
     * @return the Newartaskid
     */
    public String getNewartaskid() {
        return (String) getAttributeInternal(NEWARTASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Newartaskid.
     * @param value value to set the  Newartaskid
     */
    public void setNewartaskid(String value) {
        setAttributeInternal(NEWARTASKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Newratetype.
     * @return the Newratetype
     */
    public String getNewratetype() {
        return (String) getAttributeInternal(NEWRATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Newratetype.
     * @param value value to set the  Newratetype
     */
    public void setNewratetype(String value) {
        setAttributeInternal(NEWRATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Equipcharge.
     * @return the Equipcharge
     */
    public String getEquipcharge() {
        return (String) getAttributeInternal(EQUIPCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Equipcharge.
     * @param value value to set the  Equipcharge
     */
    public void setEquipcharge(String value) {
        setAttributeInternal(EQUIPCHARGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Newrate.
     * @return the Newrate
     */
    public Double getNewrate() {
        return (Double) getAttributeInternal(NEWRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Newrate.
     * @param value value to set the  Newrate
     */
    public void setNewrate(Double value) {
        setAttributeInternal(NEWRATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rtroratetype.
     * @return the Rtroratetype
     */
    public String getRtroratetype() {
        return (String) getAttributeInternal(RTRORATETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rtroratetype.
     * @param value value to set the  Rtroratetype
     */
    public void setRtroratetype(String value) {
        setAttributeInternal(RTRORATETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rtrover.
     * @return the Rtrover
     */
    public String getRtrover() {
        return (String) getAttributeInternal(RTROVER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rtrover.
     * @param value value to set the  Rtrover
     */
    public void setRtrover(String value) {
        setAttributeInternal(RTROVER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rtronewartaskid.
     * @return the Rtronewartaskid
     */
    public String getRtronewartaskid() {
        return (String) getAttributeInternal(RTRONEWARTASKID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rtronewartaskid.
     * @param value value to set the  Rtronewartaskid
     */
    public void setRtronewartaskid(String value) {
        setAttributeInternal(RTRONEWARTASKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Rtrorate.
     * @return the Rtrorate
     */
    public Double getRtrorate() {
        return (Double) getAttributeInternal(RTRORATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Rtrorate.
     * @param value value to set the  Rtrorate
     */
    public void setRtrorate(Double value) {
        setAttributeInternal(RTRORATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreditDebit.
     * @return the CreditDebit
     */
    public Double getCreditDebit() {
        return (Double) getAttributeInternal(CREDITDEBIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreditDebit.
     * @param value value to set the  CreditDebit
     */
    public void setCreditDebit(Double value) {
        setAttributeInternal(CREDITDEBIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreditDebitSum.
     * @return the CreditDebitSum
     */
    public Double getCreditDebitSum() {
        return (Double) getAttributeInternal(CREDITDEBITSUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreditDebitSum.
     * @param value value to set the  CreditDebitSum
     */
    public void setCreditDebitSum(Double value) {
        setAttributeInternal(CREDITDEBITSUM, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MrltInvoiceheaderView.
     */
    public RowSet getMrltInvoiceheaderView() {
        return (RowSet)getAttributeInternal(MRLTINVOICEHEADERVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MrltInvoicertroitemView.
     */
    public RowSet getMrltInvoicertroitemView() {
        return (RowSet)getAttributeInternal(MRLTINVOICERTROITEMVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
