package its.mnr.mp5.vo.asset;

import its.mnr.mp5.baseclass.ExtendedViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 06 10:54:16 PDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MrltAssetViewImpl extends ExtendedViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MrltAssetViewImpl() {
    }

    /**
     * Returns the variable value for BindAssetCd.
     * @return variable value for BindAssetCd
     */
    public String getBindAssetCd() {
        return (String)ensureVariableManager().getVariableValue("BindAssetCd");
    }

    /**
     * Sets <code>value</code> for variable BindAssetCd.
     * @param value value to bind as BindAssetCd
     */
    public void setBindAssetCd(String value) {
        ensureVariableManager().setVariableValue("BindAssetCd", value);
    }

    /**
     * Returns the variable value for BindAssetOrg.
     * @return variable value for BindAssetOrg
     */
    public String getBindAssetOrg() {
        return (String)ensureVariableManager().getVariableValue("BindAssetOrg");
    }

    /**
     * Sets <code>value</code> for variable BindAssetOrg.
     * @param value value to bind as BindAssetOrg
     */
    public void setBindAssetOrg(String value) {
        ensureVariableManager().setVariableValue("BindAssetOrg", value);
    }
}
