package its.mnr.mp5.eo.local;

import its.mnr.mp5.baseclass.ExtendedEntityImpl;

import its.mnr.mp5.baseclass.ExtendedViewRowImpl;

import its.mnr.mp5.vo.parts.SuppliersImpl;

import its.mnr.mp5.vo.workorder.TransactionsImpl;

import java.math.BigDecimal;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.VariableValueManager;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 05 15:49:52 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class R5partsImpl extends ExtendedEntityImpl {
    
    public static int VARCHAR2 = Types.VARCHAR;
    
    /* Helper methods */    
    protected Object callStoredFunction(int sqlReturnType, String stmt, Object[] bindVars) {
        CallableStatement st = null;
        try {
            // 1. Create a JDBC CallabledStatement
            st = getDBTransaction().createCallableStatement("begin ? := " + stmt + ";end;", 0);
            // 2. Register the first bind variable for the return value
            st.registerOutParameter(1, sqlReturnType);
            if (bindVars != null) {
                // 3. Loop over values for the bind variables passed in, if any
                for (int z = 0; z < bindVars.length; z++) {
                    // 4. Set the value of user-supplied bind vars in the stmt
                    st.setObject(z + 2, bindVars[z]);
                }
            }
            // 5. Set the value of user-supplied bind vars in the stmt
            st.executeUpdate();
            // 6. Return the value of the first bind variable
            return st.getObject(1);
        } catch (SQLException e) {
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    // 7. Close the statement
                    st.close();
                } catch (SQLException e) {
                }
            }
        }
    }
    
    public String CatalogueUpd(String pPart, String pPartOrg, String pSupp, String pSuppOrg, Double pPurPrice, String pUom, Double pMultiply, String pCurr, String pTax) {
             //System.out.println("CatalogueUpd function() ");
             
             String ret = (String)callStoredFunction(VARCHAR2, "mnrpkg.CATALOGUEUPD(?,?,?,?,?,?,?,?,?)",
                                               new Object[] {pPart,pPartOrg,pSupp,pSuppOrg,pPurPrice,pUom,pMultiply,pCurr,pTax});
             //System.out.println("ITS_EstimateUpd Ret = " + ret);
             return ret;
         }

    public void createPreSupplier(){
        //System.out.println("createPreSupplier()");

        String pPart =this.getParCode(); 
        String pPartOrg =this.getParOrg(); 
        String pSupp =this.getParPrefsup(); 
        String pSuppOrg =this.getParPrefsupOrg(); 
        Double dPurPrice = this.getParPrefsupprice();
        String pUom =this.getParUom(); 
        Double dMultiply = null;
        String pCurr = "USD"; 
        String pTax = this.getParTax();

        if (!isPrefSuppInCat(pPart, pPartOrg, pSupp, pSuppOrg)) {
            RowIterator iterCat = getR5catalogue();
            Row rowCat = iterCat.createRow();
            iterCat.insertRow(rowCat);

            rowCat.setAttribute("CatPart", pPart);
            rowCat.setAttribute("CatPartOrg", pPartOrg);
            rowCat.setAttribute("CatSupplier", pSupp);
            rowCat.setAttribute("CatSupplierOrg", pSuppOrg);
            rowCat.setAttribute("CatPurprice", dPurPrice);
            rowCat.setAttribute("CatPuruom", pUom);
            rowCat.setAttribute("CatMultiply", dMultiply);
            rowCat.setAttribute("CatCurr", pCurr);
            rowCat.setAttribute("CatTax", pTax);
            rowCat.setAttribute("CatDate", new Timestamp(new java.sql.Timestamp(System.currentTimeMillis())));

        }
        }

    public void createStock() {
        //System.out.println("createStock()");

        String pPart = this.getParCode();
        String pPartOrg = this.getParOrg();
        String pStore = "01";


        RowIterator iterCat = getR5stock();
        Row rowCat = iterCat.createRow();
        iterCat.insertRow(rowCat);

        rowCat.setAttribute("StoPart", pPart);
        rowCat.setAttribute("StoPartOrg", pPartOrg);
        rowCat.setAttribute("StoStore", pStore);
        rowCat.setAttribute("StoQty", 0.0);

    }
    
    public void updStockPrefSup() {
        //System.out.println("updStockPrefSup()");

        RowIterator iter = getR5stock();
        Row row = iter.first(); 

        //System.out.println(row.getAttribute("StoPart"));
        
        row.setAttribute("StoPrefsup", getParPrefsup());
        row.setAttribute("StoPrefsupOrg", getParPrefsupOrg());

    }
    
    public boolean isPrefSuppInCat(String pPart, String pPartOrg, String pSupp, String pSuppOrg) {
        //System.out.println("isPrefSuppInCat");
        boolean ret = false;
        RowSet rs = this.getSupplierExistenceChk();
        VariableValueManager vm = rs.ensureVariableManager();
        vm.setVariableValue("BPART", pPart);
        vm.setVariableValue("BPARTORG", pPartOrg);
        vm.setVariableValue("BSUPP", pSupp);
        vm.setVariableValue("BSUPPORG", pSuppOrg);
        rs.setForwardOnly(true);
        rs.executeQuery();
        Row rw = rs.first();
        if (rw != null) {
            ret = true;
        }
        return ret;
    }
    
    protected void doDML(int operation, TransactionEvent transactionEvent) {
        //System.out.println("R5parts doDML");
        
        /**
          * Business Rule calls
          */
        if (operation == DML_INSERT ) {
            createStock();
        }   
        if ((operation == DML_INSERT || operation == DML_UPDATE) && isAttributeChanged(PARPREFSUP)) {
            createPreSupplier();
        }
        if ((operation == DML_UPDATE) && isAttributeChanged(PARPREFSUP)) {
            updStockPrefSup();
        }
        super.doDML(operation, transactionEvent);
    }


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ParCode {
            public Object get(R5partsImpl obj) {
                return obj.getParCode();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCode((String)value);
            }
        }
        ,
        ParDesc {
            public Object get(R5partsImpl obj) {
                return obj.getParDesc();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParDesc((String)value);
            }
        }
        ,
        ParClass {
            public Object get(R5partsImpl obj) {
                return obj.getParClass();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParClass((String)value);
            }
        }
        ,
        ParUom {
            public Object get(R5partsImpl obj) {
                return obj.getParUom();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParUom((String)value);
            }
        }
        ,
        ParByasset {
            public Object get(R5partsImpl obj) {
                return obj.getParByasset();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParByasset((String)value);
            }
        }
        ,
        ParBylot {
            public Object get(R5partsImpl obj) {
                return obj.getParBylot();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParBylot((String)value);
            }
        }
        ,
        ParCategory {
            public Object get(R5partsImpl obj) {
                return obj.getParCategory();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCategory((String)value);
            }
        }
        ,
        ParBaseprice {
            public Object get(R5partsImpl obj) {
                return obj.getParBaseprice();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParBaseprice((Double)value);
            }
        }
        ,
        ParAvgprice {
            public Object get(R5partsImpl obj) {
                return obj.getParAvgprice();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParAvgprice((Double)value);
            }
        }
        ,
        ParLastprice {
            public Object get(R5partsImpl obj) {
                return obj.getParLastprice();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParLastprice((Double)value);
            }
        }
        ,
        ParStdprice {
            public Object get(R5partsImpl obj) {
                return obj.getParStdprice();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParStdprice((Double)value);
            }
        }
        ,
        ParPrefsup {
            public Object get(R5partsImpl obj) {
                return obj.getParPrefsup();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParPrefsup((String)value);
            }
        }
        ,
        ParPrefsupprice {
            public Object get(R5partsImpl obj) {
                return obj.getParPrefsupprice();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParPrefsupprice((Double)value);
            }
        }
        ,
        ParPrefuom {
            public Object get(R5partsImpl obj) {
                return obj.getParPrefuom();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParPrefuom((String)value);
            }
        }
        ,
        ParCommodity {
            public Object get(R5partsImpl obj) {
                return obj.getParCommodity();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCommodity((String)value);
            }
        }
        ,
        ParSubcommodity {
            public Object get(R5partsImpl obj) {
                return obj.getParSubcommodity();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParSubcommodity((String)value);
            }
        }
        ,
        ParTax {
            public Object get(R5partsImpl obj) {
                return obj.getParTax();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParTax((String)value);
            }
        }
        ,
        ParBuyer {
            public Object get(R5partsImpl obj) {
                return obj.getParBuyer();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParBuyer((String)value);
            }
        }
        ,
        ParSourcesystem {
            public Object get(R5partsImpl obj) {
                return obj.getParSourcesystem();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParSourcesystem((String)value);
            }
        }
        ,
        ParSourcecode {
            public Object get(R5partsImpl obj) {
                return obj.getParSourcecode();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParSourcecode((String)value);
            }
        }
        ,
        ParInterface {
            public Object get(R5partsImpl obj) {
                return obj.getParInterface();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParInterface((Timestamp)value);
            }
        }
        ,
        ParNotused {
            public Object get(R5partsImpl obj) {
                return obj.getParNotused();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParNotused((String)value);
            }
        }
        ,
        ParTracktype {
            public Object get(R5partsImpl obj) {
                return obj.getParTracktype();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParTracktype((String)value);
            }
        }
        ,
        ParTrackrtype {
            public Object get(R5partsImpl obj) {
                return obj.getParTrackrtype();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParTrackrtype((String)value);
            }
        }
        ,
        ParTool {
            public Object get(R5partsImpl obj) {
                return obj.getParTool();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParTool((String)value);
            }
        }
        ,
        ParWardays {
            public Object get(R5partsImpl obj) {
                return obj.getParWardays();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParWardays((Integer)value);
            }
        }
        ,
        ParOrg {
            public Object get(R5partsImpl obj) {
                return obj.getParOrg();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParOrg((String)value);
            }
        }
        ,
        ParClassOrg {
            public Object get(R5partsImpl obj) {
                return obj.getParClassOrg();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParClassOrg((String)value);
            }
        }
        ,
        ParPrefsupOrg {
            public Object get(R5partsImpl obj) {
                return obj.getParPrefsupOrg();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParPrefsupOrg((String)value);
            }
        }
        ,
        ParInspect {
            public Object get(R5partsImpl obj) {
                return obj.getParInspect();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParInspect((String)value);
            }
        }
        ,
        ParInsmethod {
            public Object get(R5partsImpl obj) {
                return obj.getParInsmethod();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParInsmethod((String)value);
            }
        }
        ,
        ParCodestructure {
            public Object get(R5partsImpl obj) {
                return obj.getParCodestructure();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCodestructure((String)value);
            }
        }
        ,
        ParCreated {
            public Object get(R5partsImpl obj) {
                return obj.getParCreated();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCreated((Timestamp)value);
            }
        }
        ,
        ParCreatedby {
            public Object get(R5partsImpl obj) {
                return obj.getParCreatedby();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParCreatedby((String)value);
            }
        }
        ,
        ParUpdated {
            public Object get(R5partsImpl obj) {
                return obj.getParUpdated();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParUpdated((Timestamp)value);
            }
        }
        ,
        ParUpdatedby {
            public Object get(R5partsImpl obj) {
                return obj.getParUpdatedby();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setParUpdatedby((String)value);
            }
        }
        ,
        ItsCyclecnt {
            public Object get(R5partsImpl obj) {
                return obj.getItsCyclecnt();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setItsCyclecnt((String)value);
            }
        }
        ,
        ItsGl {
            public Object get(R5partsImpl obj) {
                return obj.getItsGl();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setItsGl((String)value);
            }
        }
        ,
        tParCode {
            public Object get(R5partsImpl obj) {
                return obj.gettParCode();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.settParCode((String)value);
            }
        }
        ,
        tTotalStoQty {
            public Object get(R5partsImpl obj) {
                return obj.gettTotalStoQty();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.settTotalStoQty((Double)value);
            }
        }
        ,
        tPostedParNotused {
            public Object get(R5partsImpl obj) {
                return obj.gettPostedParNotused();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.settPostedParNotused((String)value);
            }
        }
        ,
        R5matlparts {
            public Object get(R5partsImpl obj) {
                return obj.getR5matlparts();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5objects {
            public Object get(R5partsImpl obj) {
                return obj.getR5objects();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5translines {
            public Object get(R5partsImpl obj) {
                return obj.getR5translines();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5binstock {
            public Object get(R5partsImpl obj) {
                return obj.getR5binstock();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5uoms {
            public Object get(R5partsImpl obj) {
                return obj.getR5uoms();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setR5uoms((ExtendedEntityImpl)value);
            }
        }
        ,
        R5taxrates {
            public Object get(R5partsImpl obj) {
                return obj.getR5taxrates();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setR5taxrates((ExtendedEntityImpl)value);
            }
        }
        ,
        R5companies {
            public Object get(R5partsImpl obj) {
                return obj.getR5companies();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setR5companies((ExtendedEntityImpl)value);
            }
        }
        ,
        R5catalogue {
            public Object get(R5partsImpl obj) {
                return obj.getR5catalogue();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5addetails {
            public Object get(R5partsImpl obj) {
                return obj.getR5addetails();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5stock {
            public Object get(R5partsImpl obj) {
                return obj.getR5stock();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5orderlines {
            public Object get(R5partsImpl obj) {
                return obj.getR5orderlines();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setR5orderlines((R5orderlinesImpl)value);
            }
        }
        ,
        MrltSpares {
            public Object get(R5partsImpl obj) {
                return obj.getMrltSpares();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setMrltSpares((ExtendedEntityImpl)value);
            }
        }
        ,
        SupplierPref {
            public Object get(R5partsImpl obj) {
                return obj.getSupplierPref();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierExistenceChk {
            public Object get(R5partsImpl obj) {
                return obj.getSupplierExistenceChk();
            }

            public void put(R5partsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(R5partsImpl object);

        public abstract void put(R5partsImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PARCODE = AttributesEnum.ParCode.index();
    public static final int PARDESC = AttributesEnum.ParDesc.index();
    public static final int PARCLASS = AttributesEnum.ParClass.index();
    public static final int PARUOM = AttributesEnum.ParUom.index();
    public static final int PARBYASSET = AttributesEnum.ParByasset.index();
    public static final int PARBYLOT = AttributesEnum.ParBylot.index();
    public static final int PARCATEGORY = AttributesEnum.ParCategory.index();
    public static final int PARBASEPRICE = AttributesEnum.ParBaseprice.index();
    public static final int PARAVGPRICE = AttributesEnum.ParAvgprice.index();
    public static final int PARLASTPRICE = AttributesEnum.ParLastprice.index();
    public static final int PARSTDPRICE = AttributesEnum.ParStdprice.index();
    public static final int PARPREFSUP = AttributesEnum.ParPrefsup.index();
    public static final int PARPREFSUPPRICE = AttributesEnum.ParPrefsupprice.index();
    public static final int PARPREFUOM = AttributesEnum.ParPrefuom.index();
    public static final int PARCOMMODITY = AttributesEnum.ParCommodity.index();
    public static final int PARSUBCOMMODITY = AttributesEnum.ParSubcommodity.index();
    public static final int PARTAX = AttributesEnum.ParTax.index();
    public static final int PARBUYER = AttributesEnum.ParBuyer.index();
    public static final int PARSOURCESYSTEM = AttributesEnum.ParSourcesystem.index();
    public static final int PARSOURCECODE = AttributesEnum.ParSourcecode.index();
    public static final int PARINTERFACE = AttributesEnum.ParInterface.index();
    public static final int PARNOTUSED = AttributesEnum.ParNotused.index();
    public static final int PARTRACKTYPE = AttributesEnum.ParTracktype.index();
    public static final int PARTRACKRTYPE = AttributesEnum.ParTrackrtype.index();
    public static final int PARTOOL = AttributesEnum.ParTool.index();
    public static final int PARWARDAYS = AttributesEnum.ParWardays.index();
    public static final int PARORG = AttributesEnum.ParOrg.index();
    public static final int PARCLASSORG = AttributesEnum.ParClassOrg.index();
    public static final int PARPREFSUPORG = AttributesEnum.ParPrefsupOrg.index();
    public static final int PARINSPECT = AttributesEnum.ParInspect.index();
    public static final int PARINSMETHOD = AttributesEnum.ParInsmethod.index();
    public static final int PARCODESTRUCTURE = AttributesEnum.ParCodestructure.index();
    public static final int PARCREATED = AttributesEnum.ParCreated.index();
    public static final int PARCREATEDBY = AttributesEnum.ParCreatedby.index();
    public static final int PARUPDATED = AttributesEnum.ParUpdated.index();
    public static final int PARUPDATEDBY = AttributesEnum.ParUpdatedby.index();
    public static final int ITSCYCLECNT = AttributesEnum.ItsCyclecnt.index();
    public static final int ITSGL = AttributesEnum.ItsGl.index();
    public static final int TPARCODE = AttributesEnum.tParCode.index();
    public static final int TTOTALSTOQTY = AttributesEnum.tTotalStoQty.index();
    public static final int TPOSTEDPARNOTUSED = AttributesEnum.tPostedParNotused.index();
    public static final int R5MATLPARTS = AttributesEnum.R5matlparts.index();
    public static final int R5OBJECTS = AttributesEnum.R5objects.index();
    public static final int R5TRANSLINES = AttributesEnum.R5translines.index();
    public static final int R5BINSTOCK = AttributesEnum.R5binstock.index();
    public static final int R5UOMS = AttributesEnum.R5uoms.index();
    public static final int R5TAXRATES = AttributesEnum.R5taxrates.index();
    public static final int R5COMPANIES = AttributesEnum.R5companies.index();
    public static final int R5CATALOGUE = AttributesEnum.R5catalogue.index();
    public static final int R5ADDETAILS = AttributesEnum.R5addetails.index();
    public static final int R5STOCK = AttributesEnum.R5stock.index();
    public static final int R5ORDERLINES = AttributesEnum.R5orderlines.index();
    public static final int MRLTSPARES = AttributesEnum.MrltSpares.index();
    public static final int SUPPLIERPREF = AttributesEnum.SupplierPref.index();
    public static final int SUPPLIEREXISTENCECHK = AttributesEnum.SupplierExistenceChk.index();

    /**
     * This is the default constructor (do not remove).
     */
    public R5partsImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("its.mnr.mp5.eo.local.R5parts");
    }

    /**
     * Gets the attribute value for ParCode, using the alias name ParCode.
     * @return the value of ParCode
     */
    public String getParCode() {
        return (String)getAttributeInternal(PARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCode.
     * @param value value to set the ParCode
     */
    public void setParCode(String value) {
        setAttributeInternal(PARCODE, value.toUpperCase());
    }

    /**
     * Gets the attribute value for ParDesc, using the alias name ParDesc.
     * @return the value of ParDesc
     */
    public String getParDesc() {
        return (String)getAttributeInternal(PARDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParDesc.
     * @param value value to set the ParDesc
     */
    public void setParDesc(String value) {
        setAttributeInternal(PARDESC, value);
    }

    /**
     * Gets the attribute value for ParClass, using the alias name ParClass.
     * @return the value of ParClass
     */
    public String getParClass() {
        return (String)getAttributeInternal(PARCLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParClass.
     * @param value value to set the ParClass
     */
    public void setParClass(String value) {
        setAttributeInternal(PARCLASS, value);
    }

    /**
     * Gets the attribute value for ParUom, using the alias name ParUom.
     * @return the value of ParUom
     */
    public String getParUom() {
        return (String)getAttributeInternal(PARUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParUom.
     * @param value value to set the ParUom
     */
    public void setParUom(String value) {
        setAttributeInternal(PARUOM, value);
    }

    /**
     * Gets the attribute value for ParByasset, using the alias name ParByasset.
     * @return the value of ParByasset
     */
    public String getParByasset() {
        return (String)getAttributeInternal(PARBYASSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParByasset.
     * @param value value to set the ParByasset
     */
    public void setParByasset(String value) {
        setAttributeInternal(PARBYASSET, value);
    }

    /**
     * Gets the attribute value for ParBylot, using the alias name ParBylot.
     * @return the value of ParBylot
     */
    public String getParBylot() {
        return (String)getAttributeInternal(PARBYLOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParBylot.
     * @param value value to set the ParBylot
     */
    public void setParBylot(String value) {
        setAttributeInternal(PARBYLOT, value);
    }

    /**
     * Gets the attribute value for ParCategory, using the alias name ParCategory.
     * @return the value of ParCategory
     */
    public String getParCategory() {
        return (String)getAttributeInternal(PARCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCategory.
     * @param value value to set the ParCategory
     */
    public void setParCategory(String value) {
        setAttributeInternal(PARCATEGORY, value);
    }

    /**
     * Gets the attribute value for ParBaseprice, using the alias name ParBaseprice.
     * @return the value of ParBaseprice
     */
    public Double getParBaseprice() {
        return (Double)getAttributeInternal(PARBASEPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParBaseprice.
     * @param value value to set the ParBaseprice
     */
    public void setParBaseprice(Double value) {
        setAttributeInternal(PARBASEPRICE, value);
    }

    /**
     * Gets the attribute value for ParAvgprice, using the alias name ParAvgprice.
     * @return the value of ParAvgprice
     */
    public Double getParAvgprice() {
        return (Double)getAttributeInternal(PARAVGPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParAvgprice.
     * @param value value to set the ParAvgprice
     */
    public void setParAvgprice(Double value) {
        setAttributeInternal(PARAVGPRICE, value);
    }

    /**
     * Gets the attribute value for ParLastprice, using the alias name ParLastprice.
     * @return the value of ParLastprice
     */
    public Double getParLastprice() {
        return (Double)getAttributeInternal(PARLASTPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParLastprice.
     * @param value value to set the ParLastprice
     */
    public void setParLastprice(Double value) {
        setAttributeInternal(PARLASTPRICE, value);
    }

    /**
     * Gets the attribute value for ParStdprice, using the alias name ParStdprice.
     * @return the value of ParStdprice
     */
    public Double getParStdprice() {
        return (Double)getAttributeInternal(PARSTDPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParStdprice.
     * @param value value to set the ParStdprice
     */
    public void setParStdprice(Double value) {
        setAttributeInternal(PARSTDPRICE, value);
    }

    /**
     * Gets the attribute value for ParPrefsup, using the alias name ParPrefsup.
     * @return the value of ParPrefsup
     */
    public String getParPrefsup() {
        return (String)getAttributeInternal(PARPREFSUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParPrefsup.
     * @param value value to set the ParPrefsup
     */
    public void setParPrefsup(String value) {
        setAttributeInternal(PARPREFSUP, value);
    }

    /**
     * Gets the attribute value for ParPrefsupprice, using the alias name ParPrefsupprice.
     * @return the value of ParPrefsupprice
     */
    public Double getParPrefsupprice() {
        return (Double)getAttributeInternal(PARPREFSUPPRICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParPrefsupprice.
     * @param value value to set the ParPrefsupprice
     */
    public void setParPrefsupprice(Double value) {
        setAttributeInternal(PARPREFSUPPRICE, value);
    }

    /**
     * Gets the attribute value for ParPrefuom, using the alias name ParPrefuom.
     * @return the value of ParPrefuom
     */
    public String getParPrefuom() {
        return (String)getAttributeInternal(PARPREFUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParPrefuom.
     * @param value value to set the ParPrefuom
     */
    public void setParPrefuom(String value) {
        setAttributeInternal(PARPREFUOM, value);
    }

    /**
     * Gets the attribute value for ParCommodity, using the alias name ParCommodity.
     * @return the value of ParCommodity
     */
    public String getParCommodity() {
        return (String)getAttributeInternal(PARCOMMODITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCommodity.
     * @param value value to set the ParCommodity
     */
    public void setParCommodity(String value) {
        setAttributeInternal(PARCOMMODITY, value);
    }

    /**
     * Gets the attribute value for ParSubcommodity, using the alias name ParSubcommodity.
     * @return the value of ParSubcommodity
     */
    public String getParSubcommodity() {
        return (String)getAttributeInternal(PARSUBCOMMODITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParSubcommodity.
     * @param value value to set the ParSubcommodity
     */
    public void setParSubcommodity(String value) {
        setAttributeInternal(PARSUBCOMMODITY, value);
    }

    /**
     * Gets the attribute value for ParTax, using the alias name ParTax.
     * @return the value of ParTax
     */
    public String getParTax() {
        return (String)getAttributeInternal(PARTAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParTax.
     * @param value value to set the ParTax
     */
    public void setParTax(String value) {
        setAttributeInternal(PARTAX, value);
    }

    /**
     * Gets the attribute value for ParBuyer, using the alias name ParBuyer.
     * @return the value of ParBuyer
     */
    public String getParBuyer() {
        return (String)getAttributeInternal(PARBUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParBuyer.
     * @param value value to set the ParBuyer
     */
    public void setParBuyer(String value) {
        setAttributeInternal(PARBUYER, value);
    }

    /**
     * Gets the attribute value for ParSourcesystem, using the alias name ParSourcesystem.
     * @return the value of ParSourcesystem
     */
    public String getParSourcesystem() {
        return (String)getAttributeInternal(PARSOURCESYSTEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParSourcesystem.
     * @param value value to set the ParSourcesystem
     */
    public void setParSourcesystem(String value) {
        setAttributeInternal(PARSOURCESYSTEM, value);
    }

    /**
     * Gets the attribute value for ParSourcecode, using the alias name ParSourcecode.
     * @return the value of ParSourcecode
     */
    public String getParSourcecode() {
        return (String)getAttributeInternal(PARSOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParSourcecode.
     * @param value value to set the ParSourcecode
     */
    public void setParSourcecode(String value) {
        setAttributeInternal(PARSOURCECODE, value);
    }

    /**
     * Gets the attribute value for ParInterface, using the alias name ParInterface.
     * @return the value of ParInterface
     */
    public Timestamp getParInterface() {
        return (Timestamp)getAttributeInternal(PARINTERFACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParInterface.
     * @param value value to set the ParInterface
     */
    public void setParInterface(Timestamp value) {
        setAttributeInternal(PARINTERFACE, value);
    }

    /**
     * Gets the attribute value for ParNotused, using the alias name ParNotused.
     * @return the value of ParNotused
     */
    public String getParNotused() {
        return (String)getAttributeInternal(PARNOTUSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParNotused.
     * @param value value to set the ParNotused
     */
    public void setParNotused(String value) {
        setAttributeInternal(PARNOTUSED, value);
    }

    /**
     * Gets the attribute value for ParTracktype, using the alias name ParTracktype.
     * @return the value of ParTracktype
     */
    public String getParTracktype() {
        return (String)getAttributeInternal(PARTRACKTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParTracktype.
     * @param value value to set the ParTracktype
     */
    public void setParTracktype(String value) {
        setAttributeInternal(PARTRACKTYPE, value);
    }

    /**
     * Gets the attribute value for ParTrackrtype, using the alias name ParTrackrtype.
     * @return the value of ParTrackrtype
     */
    public String getParTrackrtype() {
        return (String)getAttributeInternal(PARTRACKRTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParTrackrtype.
     * @param value value to set the ParTrackrtype
     */
    public void setParTrackrtype(String value) {
        setAttributeInternal(PARTRACKRTYPE, value);
    }

    /**
     * Gets the attribute value for ParTool, using the alias name ParTool.
     * @return the value of ParTool
     */
    public String getParTool() {
        return (String)getAttributeInternal(PARTOOL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParTool.
     * @param value value to set the ParTool
     */
    public void setParTool(String value) {
        setAttributeInternal(PARTOOL, value);
    }

    /**
     * Gets the attribute value for ParWardays, using the alias name ParWardays.
     * @return the value of ParWardays
     */
    public Integer getParWardays() {
        return (Integer)getAttributeInternal(PARWARDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParWardays.
     * @param value value to set the ParWardays
     */
    public void setParWardays(Integer value) {
        setAttributeInternal(PARWARDAYS, value);
    }

    /**
     * Gets the attribute value for ParOrg, using the alias name ParOrg.
     * @return the value of ParOrg
     */
    public String getParOrg() {
        return (String)getAttributeInternal(PARORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParOrg.
     * @param value value to set the ParOrg
     */
    public void setParOrg(String value) {
        setAttributeInternal(PARORG, value);
    }

    /**
     * Gets the attribute value for ParClassOrg, using the alias name ParClassOrg.
     * @return the value of ParClassOrg
     */
    public String getParClassOrg() {
        return (String)getAttributeInternal(PARCLASSORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParClassOrg.
     * @param value value to set the ParClassOrg
     */
    public void setParClassOrg(String value) {
        setAttributeInternal(PARCLASSORG, value);
    }

    /**
     * Gets the attribute value for ParPrefsupOrg, using the alias name ParPrefsupOrg.
     * @return the value of ParPrefsupOrg
     */
    public String getParPrefsupOrg() {
        return (String)getAttributeInternal(PARPREFSUPORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParPrefsupOrg.
     * @param value value to set the ParPrefsupOrg
     */
    public void setParPrefsupOrg(String value) {
        setAttributeInternal(PARPREFSUPORG, value);
    }

    /**
     * Gets the attribute value for ParInspect, using the alias name ParInspect.
     * @return the value of ParInspect
     */
    public String getParInspect() {
        return (String)getAttributeInternal(PARINSPECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParInspect.
     * @param value value to set the ParInspect
     */
    public void setParInspect(String value) {
        setAttributeInternal(PARINSPECT, value);
    }

    /**
     * Gets the attribute value for ParInsmethod, using the alias name ParInsmethod.
     * @return the value of ParInsmethod
     */
    public String getParInsmethod() {
        return (String)getAttributeInternal(PARINSMETHOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParInsmethod.
     * @param value value to set the ParInsmethod
     */
    public void setParInsmethod(String value) {
        setAttributeInternal(PARINSMETHOD, value);
    }

    /**
     * Gets the attribute value for ParCodestructure, using the alias name ParCodestructure.
     * @return the value of ParCodestructure
     */
    public String getParCodestructure() {
        return (String)getAttributeInternal(PARCODESTRUCTURE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCodestructure.
     * @param value value to set the ParCodestructure
     */
    public void setParCodestructure(String value) {
        setAttributeInternal(PARCODESTRUCTURE, value);
    }

    /**
     * Gets the attribute value for ParCreated, using the alias name ParCreated.
     * @return the value of ParCreated
     */
    public Timestamp getParCreated() {
        return (Timestamp)getAttributeInternal(PARCREATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCreated.
     * @param value value to set the ParCreated
     */
    public void setParCreated(Timestamp value) {
        setAttributeInternal(PARCREATED, value);
    }

    /**
     * Gets the attribute value for ParCreatedby, using the alias name ParCreatedby.
     * @return the value of ParCreatedby
     */
    public String getParCreatedby() {
        return (String)getAttributeInternal(PARCREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParCreatedby.
     * @param value value to set the ParCreatedby
     */
    public void setParCreatedby(String value) {
        setAttributeInternal(PARCREATEDBY, value);
    }

    /**
     * Gets the attribute value for ParUpdated, using the alias name ParUpdated.
     * @return the value of ParUpdated
     */
    public Timestamp getParUpdated() {
        return (Timestamp)getAttributeInternal(PARUPDATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParUpdated.
     * @param value value to set the ParUpdated
     */
    public void setParUpdated(Timestamp value) {
        setAttributeInternal(PARUPDATED, value);
    }

    /**
     * Gets the attribute value for ParUpdatedby, using the alias name ParUpdatedby.
     * @return the value of ParUpdatedby
     */
    public String getParUpdatedby() {
        return (String)getAttributeInternal(PARUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParUpdatedby.
     * @param value value to set the ParUpdatedby
     */
    public void setParUpdatedby(String value) {
        setAttributeInternal(PARUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for ItsCyclecnt, using the alias name ItsCyclecnt.
     * @return the value of ItsCyclecnt
     */
    public String getItsCyclecnt() {
        return (String)getAttributeInternal(ITSCYCLECNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItsCyclecnt.
     * @param value value to set the ItsCyclecnt
     */
    public void setItsCyclecnt(String value) {
        setAttributeInternal(ITSCYCLECNT, value);
    }

    /**
     * Gets the attribute value for ItsGl, using the alias name ItsGl.
     * @return the value of ItsGl
     */
    public String getItsGl() {
        return (String)getAttributeInternal(ITSGL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItsGl.
     * @param value value to set the ItsGl
     */
    public void setItsGl(String value) {
        System.out.println("Inside R5partsImpl setItsGl");
        setAttributeInternal(ITSGL, value);
    }

    /**
     * Gets the attribute value for tParCode, using the alias name tParCode.
     * @return the value of tParCode
     */
    public String gettParCode() {
        return (String)getAttributeInternal(TPARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for tParCode.
     * @param value value to set the tParCode
     */
    public void settParCode(String value) {
        setAttributeInternal(TPARCODE, value);
    }

    /**
     * Gets the attribute value for tTotalStoQty, using the alias name tTotalStoQty.
     * @return the value of tTotalStoQty
     */
    public Double gettTotalStoQty() {
        return (Double)getAttributeInternal(TTOTALSTOQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for tTotalStoQty.
     * @param value value to set the tTotalStoQty
     */
    public void settTotalStoQty(Double value) {
        setAttributeInternal(TTOTALSTOQTY, value);
    }

    /**
     * Gets the attribute value for tPostedParNotused, using the alias name tPostedParNotused.
     * @return the value of tPostedParNotused
     */
    public String gettPostedParNotused() {
        return (String)getAttributeInternal(TPOSTEDPARNOTUSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for tPostedParNotused.
     * @param value value to set the tPostedParNotused
     */
    public void settPostedParNotused(String value) {
        setAttributeInternal(TPOSTEDPARNOTUSED, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5matlparts() {
        return (RowIterator)getAttributeInternal(R5MATLPARTS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5objects() {
        return (RowIterator)getAttributeInternal(R5OBJECTS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5translines() {
        return (RowIterator)getAttributeInternal(R5TRANSLINES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5binstock() {
        return (RowIterator)getAttributeInternal(R5BINSTOCK);
    }

    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public ExtendedEntityImpl getR5uoms() {
        return (ExtendedEntityImpl)getAttributeInternal(R5UOMS);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setR5uoms(ExtendedEntityImpl value) {
        setAttributeInternal(R5UOMS, value);
    }

    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public ExtendedEntityImpl getR5taxrates() {
        return (ExtendedEntityImpl)getAttributeInternal(R5TAXRATES);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setR5taxrates(ExtendedEntityImpl value) {
        setAttributeInternal(R5TAXRATES, value);
    }

    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public ExtendedEntityImpl getR5companies() {
        return (ExtendedEntityImpl)getAttributeInternal(R5COMPANIES);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setR5companies(ExtendedEntityImpl value) {
        setAttributeInternal(R5COMPANIES, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5catalogue() {
        return (RowIterator)getAttributeInternal(R5CATALOGUE);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5addetails() {
        return (RowIterator)getAttributeInternal(R5ADDETAILS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5stock() {
        return (RowIterator)getAttributeInternal(R5STOCK);
    }

    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public R5orderlinesImpl getR5orderlines() {
        return (R5orderlinesImpl)getAttributeInternal(R5ORDERLINES);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setR5orderlines(R5orderlinesImpl value) {
        setAttributeInternal(R5ORDERLINES, value);
    }

    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public ExtendedEntityImpl getMrltSpares() {
        return (ExtendedEntityImpl)getAttributeInternal(MRLTSPARES);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setMrltSpares(ExtendedEntityImpl value) {
        setAttributeInternal(MRLTSPARES, value);
    }

    /**
     * Uses the link PartsCompanyLink to return rows of Companies
     */
    public ExtendedViewRowImpl getSupplierPref() {
        return (ExtendedViewRowImpl)getAttributeInternal(SUPPLIERPREF);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierExistenceChk.
     */
    public RowSet getSupplierExistenceChk() {
        return (RowSet)getAttributeInternal(SUPPLIEREXISTENCECHK);
    }

    /**
     * @param parCode key constituent
     * @param parOrg key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String parCode, String parOrg) {
        return new Key(new Object[]{parCode, parOrg});
    }


}
