package its.mnr.mp5.eo.local;

import its.mnr.mp5.baseclass.ExtendedEntityImpl;

import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.VariableValueManager;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 13 10:10:05 PDT 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class R5transactionsImpl extends ExtendedEntityImpl {

    /**
     * Validation method for TraStatus.
     */
    public boolean validateTraStatusTraLineRecvdExists(String trastatus) {
    //public boolean validateTraStatusTraLineRecvdExists() {
        //false returns validition error
        boolean ret = false;
        
        RowSet rs = this.getPOTransactionExistence();
        VariableValueManager vm = rs.ensureVariableManager();
        vm.setVariableValue("bOrder", getTraOrder());
        vm.setVariableValue("vAcd", getTraAcd());
        rs.setForwardOnly(true);
        rs.executeQuery();
        Row rw = rs.first();
        if (rw != null) {
            ret = true;
        }

        return ret;
    }
    
    /**
     * BR:  Transaction Record Status must Unfinivhsed and have no parts for Delete
     *
     * */
    public void chkTransHasParts() {
//        boolean hasParts = false;
        String msg;
//        hasParts = validateTraStatusTraLineRecvdExists(getTraStatus());
        
        RowIterator iter  = getR5translines();
        int cnt = iter.getRowCount();
        if ("U".equals(getTraStatus())== false){
                msg = "Transaction Record must be Unfinished for Delete";
                throw new JboException(msg);
            }
        if (cnt > 0) {            
            msg = "Transaction Record must be empty for Delete";
            throw new JboException(msg);
        }

    }

    protected void doDML(int i, TransactionEvent transactionEvent) {
//        System.out.println("R5transactions doDML");

        /**
          * Business Rule calls
          */
        if (i == DML_DELETE) {
            chkTransHasParts();
        }
//System.out.println("getTraCode():" +getTraCode() );
//System.out.println("getTraDesc():" +getTraDesc());
//System.out.println("getTraType():" +getTraType());
//System.out.println("getTraRtype():" +getTraRtype());
//System.out.println("getTraAuth():" +getTraAuth());
//System.out.println("getTraDate():" +getTraDate());
//System.out.println("getTraOrder():" +getTraOrder());
//System.out.println("getTraStatus():" +getTraStatus());
//System.out.println("getTraRstatus():" +getTraRstatus());
//System.out.println("getTraFromentity():" +getTraFromentity());
//System.out.println("getTraFromrentity():" +getTraFromrentity());
//System.out.println("getTraFromtype():" +getTraFromtype());
//System.out.println("getTraFromrtype():"+getTraFromrtype());
//System.out.println("getTraFromcode():"+getTraFromcode());
//System.out.println("getTraToentity():" +getTraToentity());
//System.out.println("getTraTorentity():" +getTraTorentity());
//System.out.println("getTraTotype():" +getTraTotype());
//System.out.println("getTraTortype():" +getTraTortype());
//System.out.println("getTraTocode():" +getTraTocode());
//System.out.println("getTraPrinted():" +getTraPrinted());
//System.out.println("getTraAcd():" +getTraAcd());
//System.out.println("getTraOrg():" +getTraOrg());
//System.out.println("getTraFromcodeOrg():" +getTraFromcodeOrg());
//System.out.println("getTraOrderOrg():" +getTraOrderOrg());

        super.doDML(i, transactionEvent);
    }



    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TraDesc {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraDesc();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraDesc((String)value);
            }
        }
        ,
        TraClass {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraClass();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraClass((String)value);
            }
        }
        ,
        TraType {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraType();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraType((String)value);
            }
        }
        ,
        TraRtype {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraRtype();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraRtype((String)value);
            }
        }
        ,
        TraAdvice {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraAdvice();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraAdvice((String)value);
            }
        }
        ,
        TraAuth {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraAuth();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraAuth((String)value);
            }
        }
        ,
        TraDate {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraDate();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraDate((Date)value);
            }
        }
        ,
        TraOrder {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraOrder();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraOrder((String)value);
            }
        }
        ,
        TraPridest {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraPridest();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraPridest((String)value);
            }
        }
        ,
        TraPriorig {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraPriorig();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraPriorig((String)value);
            }
        }
        ,
        TraReq {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraReq();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraReq((String)value);
            }
        }
        ,
        TraStatus {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraStatus();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraStatus((String)value);
            }
        }
        ,
        TraRstatus {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraRstatus();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraRstatus((String)value);
            }
        }
        ,
        TraFromentity {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromentity();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromentity((String)value);
            }
        }
        ,
        TraFromrentity {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromrentity();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromrentity((String)value);
            }
        }
        ,
        TraFromtype {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromtype();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromtype((String)value);
            }
        }
        ,
        TraFromrtype {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromrtype();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromrtype((String)value);
            }
        }
        ,
        TraFromcode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromcode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromcode((String)value);
            }
        }
        ,
        TraToentity {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraToentity();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraToentity((String)value);
            }
        }
        ,
        TraTorentity {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraTorentity();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraTorentity((String)value);
            }
        }
        ,
        TraTotype {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraTotype();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraTotype((String)value);
            }
        }
        ,
        TraTortype {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraTortype();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraTortype((String)value);
            }
        }
        ,
        TraTocode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraTocode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraTocode((String)value);
            }
        }
        ,
        TraPrinted {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraPrinted();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraPrinted((String)value);
            }
        }
        ,
        TraSourcesystem {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraSourcesystem();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraSourcesystem((String)value);
            }
        }
        ,
        TraSourcecode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraSourcecode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraSourcecode((String)value);
            }
        }
        ,
        TraInterface {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraInterface();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraInterface((Timestamp)value);
            }
        }
        ,
        TraAcd {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraAcd();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraAcd((Number)value);
            }
        }
        ,
        TraOrg {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraOrg();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraOrg((String)value);
            }
        }
        ,
        TraClassOrg {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraClassOrg();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraClassOrg((String)value);
            }
        }
        ,
        TraTocodeOrg {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraTocodeOrg();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraTocodeOrg((String)value);
            }
        }
        ,
        TraFromcodeOrg {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraFromcodeOrg();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraFromcodeOrg((String)value);
            }
        }
        ,
        TraOrderOrg {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraOrderOrg();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraOrderOrg((String)value);
            }
        }
        ,
        TraDckcode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraDckcode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraDckcode((String)value);
            }
        }
        ,
        TraDckline {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraDckline();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraDckline((Integer)value);
            }
        }
        ,
        TraBarcode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraBarcode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraBarcode((String)value);
            }
        }
        ,
        TraCodeTransient {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraCodeTransient();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraCodeTransient((Number)value);
            }
        }
        ,
        TraCode {
            public Object get(R5transactionsImpl obj) {
                return obj.getTraCode();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setTraCode((String)value);
            }
        }
        ,
        ItsNopo {
            public Object get(R5transactionsImpl obj) {
                return obj.getItsNopo();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setItsNopo((String)value);
            }
        }
        ,
        R5translines {
            public Object get(R5transactionsImpl obj) {
                return obj.getR5translines();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5orders {
            public Object get(R5transactionsImpl obj) {
                return obj.getR5orders();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setR5orders((R5ordersImpl)value);
            }
        }
        ,
        Translines {
            public Object get(R5transactionsImpl obj) {
                return obj.getTranslines();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        POTransactionExistence {
            public Object get(R5transactionsImpl obj) {
                return obj.getPOTransactionExistence();
            }

            public void put(R5transactionsImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(R5transactionsImpl object);

        public abstract void put(R5transactionsImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRADESC = AttributesEnum.TraDesc.index();
    public static final int TRACLASS = AttributesEnum.TraClass.index();
    public static final int TRATYPE = AttributesEnum.TraType.index();
    public static final int TRARTYPE = AttributesEnum.TraRtype.index();
    public static final int TRAADVICE = AttributesEnum.TraAdvice.index();
    public static final int TRAAUTH = AttributesEnum.TraAuth.index();
    public static final int TRADATE = AttributesEnum.TraDate.index();
    public static final int TRAORDER = AttributesEnum.TraOrder.index();
    public static final int TRAPRIDEST = AttributesEnum.TraPridest.index();
    public static final int TRAPRIORIG = AttributesEnum.TraPriorig.index();
    public static final int TRAREQ = AttributesEnum.TraReq.index();
    public static final int TRASTATUS = AttributesEnum.TraStatus.index();
    public static final int TRARSTATUS = AttributesEnum.TraRstatus.index();
    public static final int TRAFROMENTITY = AttributesEnum.TraFromentity.index();
    public static final int TRAFROMRENTITY = AttributesEnum.TraFromrentity.index();
    public static final int TRAFROMTYPE = AttributesEnum.TraFromtype.index();
    public static final int TRAFROMRTYPE = AttributesEnum.TraFromrtype.index();
    public static final int TRAFROMCODE = AttributesEnum.TraFromcode.index();
    public static final int TRATOENTITY = AttributesEnum.TraToentity.index();
    public static final int TRATORENTITY = AttributesEnum.TraTorentity.index();
    public static final int TRATOTYPE = AttributesEnum.TraTotype.index();
    public static final int TRATORTYPE = AttributesEnum.TraTortype.index();
    public static final int TRATOCODE = AttributesEnum.TraTocode.index();
    public static final int TRAPRINTED = AttributesEnum.TraPrinted.index();
    public static final int TRASOURCESYSTEM = AttributesEnum.TraSourcesystem.index();
    public static final int TRASOURCECODE = AttributesEnum.TraSourcecode.index();
    public static final int TRAINTERFACE = AttributesEnum.TraInterface.index();
    public static final int TRAACD = AttributesEnum.TraAcd.index();
    public static final int TRAORG = AttributesEnum.TraOrg.index();
    public static final int TRACLASSORG = AttributesEnum.TraClassOrg.index();
    public static final int TRATOCODEORG = AttributesEnum.TraTocodeOrg.index();
    public static final int TRAFROMCODEORG = AttributesEnum.TraFromcodeOrg.index();
    public static final int TRAORDERORG = AttributesEnum.TraOrderOrg.index();
    public static final int TRADCKCODE = AttributesEnum.TraDckcode.index();
    public static final int TRADCKLINE = AttributesEnum.TraDckline.index();
    public static final int TRABARCODE = AttributesEnum.TraBarcode.index();
    public static final int TRACODETRANSIENT = AttributesEnum.TraCodeTransient.index();
    public static final int TRACODE = AttributesEnum.TraCode.index();
    public static final int ITSNOPO = AttributesEnum.ItsNopo.index();
    public static final int R5TRANSLINES = AttributesEnum.R5translines.index();
    public static final int R5ORDERS = AttributesEnum.R5orders.index();
    public static final int TRANSLINES = AttributesEnum.Translines.index();
    public static final int POTRANSACTIONEXISTENCE = AttributesEnum.POTransactionExistence.index();

    /**
     * This is the default constructor (do not remove).
     */
    public R5transactionsImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("its.mnr.mp5.eo.local.R5transactions");
    }

    /**
     * Gets the attribute value for TraDesc, using the alias name TraDesc.
     * @return the value of TraDesc
     */
    public String getTraDesc() {
        return (String)getAttributeInternal(TRADESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraDesc.
     * @param value value to set the TraDesc
     */
    public void setTraDesc(String value) {
        setAttributeInternal(TRADESC, value);
    }

    /**
     * Gets the attribute value for TraClass, using the alias name TraClass.
     * @return the value of TraClass
     */
    public String getTraClass() {
        return (String)getAttributeInternal(TRACLASS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraClass.
     * @param value value to set the TraClass
     */
    public void setTraClass(String value) {
        setAttributeInternal(TRACLASS, value);
    }

    /**
     * Gets the attribute value for TraType, using the alias name TraType.
     * @return the value of TraType
     */
    public String getTraType() {
        return (String)getAttributeInternal(TRATYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraType.
     * @param value value to set the TraType
     */
    public void setTraType(String value) {
        setAttributeInternal(TRATYPE, value);
    }

    /**
     * Gets the attribute value for TraRtype, using the alias name TraRtype.
     * @return the value of TraRtype
     */
    public String getTraRtype() {
        return (String)getAttributeInternal(TRARTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraRtype.
     * @param value value to set the TraRtype
     */
    public void setTraRtype(String value) {
        setAttributeInternal(TRARTYPE, value);
    }

    /**
     * Gets the attribute value for TraAdvice, using the alias name TraAdvice.
     * @return the value of TraAdvice
     */
    public String getTraAdvice() {
        return (String)getAttributeInternal(TRAADVICE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraAdvice.
     * @param value value to set the TraAdvice
     */
    public void setTraAdvice(String value) {
        setAttributeInternal(TRAADVICE, value);
    }

    /**
     * Gets the attribute value for TraAuth, using the alias name TraAuth.
     * @return the value of TraAuth
     */
    public String getTraAuth() {
        return (String)getAttributeInternal(TRAAUTH);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraAuth.
     * @param value value to set the TraAuth
     */
    public void setTraAuth(String value) {
        setAttributeInternal(TRAAUTH, value);
    }

    /**
     * Gets the attribute value for TraDate, using the alias name TraDate.
     * @return the value of TraDate
     */
    public Date getTraDate() {
        return (Date)getAttributeInternal(TRADATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraDate.
     * @param value value to set the TraDate
     */
    public void setTraDate(Date value) {
        setAttributeInternal(TRADATE, value);
    }

    /**
     * Gets the attribute value for TraOrder, using the alias name TraOrder.
     * @return the value of TraOrder
     */
    public String getTraOrder() {
        return (String)getAttributeInternal(TRAORDER);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraOrder.
     * @param value value to set the TraOrder
     */
    public void setTraOrder(String value) {
        setAttributeInternal(TRAORDER, value);
    }

    /**
     * Gets the attribute value for TraPridest, using the alias name TraPridest.
     * @return the value of TraPridest
     */
    public String getTraPridest() {
        return (String)getAttributeInternal(TRAPRIDEST);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraPridest.
     * @param value value to set the TraPridest
     */
    public void setTraPridest(String value) {
        setAttributeInternal(TRAPRIDEST, value);
    }

    /**
     * Gets the attribute value for TraPriorig, using the alias name TraPriorig.
     * @return the value of TraPriorig
     */
    public String getTraPriorig() {
        return (String)getAttributeInternal(TRAPRIORIG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraPriorig.
     * @param value value to set the TraPriorig
     */
    public void setTraPriorig(String value) {
        setAttributeInternal(TRAPRIORIG, value);
    }

    /**
     * Gets the attribute value for TraReq, using the alias name TraReq.
     * @return the value of TraReq
     */
    public String getTraReq() {
        return (String)getAttributeInternal(TRAREQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraReq.
     * @param value value to set the TraReq
     */
    public void setTraReq(String value) {
        setAttributeInternal(TRAREQ, value);
    }

    /**
     * Gets the attribute value for TraStatus, using the alias name TraStatus.
     * @return the value of TraStatus
     */
    public String getTraStatus() {
        return (String)getAttributeInternal(TRASTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraStatus.
     * @param value value to set the TraStatus
     */
    public void setTraStatus(String value) {
        setAttributeInternal(TRASTATUS, value);
    }

    /**
     * Gets the attribute value for TraRstatus, using the alias name TraRstatus.
     * @return the value of TraRstatus
     */
    public String getTraRstatus() {
        return (String)getAttributeInternal(TRARSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraRstatus.
     * @param value value to set the TraRstatus
     */
    public void setTraRstatus(String value) {
        setAttributeInternal(TRARSTATUS, value);
    }

    /**
     * Gets the attribute value for TraFromentity, using the alias name TraFromentity.
     * @return the value of TraFromentity
     */
    public String getTraFromentity() {
        return (String)getAttributeInternal(TRAFROMENTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromentity.
     * @param value value to set the TraFromentity
     */
    public void setTraFromentity(String value) {
        setAttributeInternal(TRAFROMENTITY, value);
    }

    /**
     * Gets the attribute value for TraFromrentity, using the alias name TraFromrentity.
     * @return the value of TraFromrentity
     */
    public String getTraFromrentity() {
        return (String)getAttributeInternal(TRAFROMRENTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromrentity.
     * @param value value to set the TraFromrentity
     */
    public void setTraFromrentity(String value) {
        setAttributeInternal(TRAFROMRENTITY, value);
    }

    /**
     * Gets the attribute value for TraFromtype, using the alias name TraFromtype.
     * @return the value of TraFromtype
     */
    public String getTraFromtype() {
        return (String)getAttributeInternal(TRAFROMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromtype.
     * @param value value to set the TraFromtype
     */
    public void setTraFromtype(String value) {
        setAttributeInternal(TRAFROMTYPE, value);
    }

    /**
     * Gets the attribute value for TraFromrtype, using the alias name TraFromrtype.
     * @return the value of TraFromrtype
     */
    public String getTraFromrtype() {
        return (String)getAttributeInternal(TRAFROMRTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromrtype.
     * @param value value to set the TraFromrtype
     */
    public void setTraFromrtype(String value) {
        setAttributeInternal(TRAFROMRTYPE, value);
    }

    /**
     * Gets the attribute value for TraFromcode, using the alias name TraFromcode.
     * @return the value of TraFromcode
     */
    public String getTraFromcode() {
        return (String)getAttributeInternal(TRAFROMCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromcode.
     * @param value value to set the TraFromcode
     */
    public void setTraFromcode(String value) {
        setAttributeInternal(TRAFROMCODE, value);
    }

    /**
     * Gets the attribute value for TraToentity, using the alias name TraToentity.
     * @return the value of TraToentity
     */
    public String getTraToentity() {
        return (String)getAttributeInternal(TRATOENTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraToentity.
     * @param value value to set the TraToentity
     */
    public void setTraToentity(String value) {
        setAttributeInternal(TRATOENTITY, value);
    }

    /**
     * Gets the attribute value for TraTorentity, using the alias name TraTorentity.
     * @return the value of TraTorentity
     */
    public String getTraTorentity() {
        return (String)getAttributeInternal(TRATORENTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraTorentity.
     * @param value value to set the TraTorentity
     */
    public void setTraTorentity(String value) {
        setAttributeInternal(TRATORENTITY, value);
    }

    /**
     * Gets the attribute value for TraTotype, using the alias name TraTotype.
     * @return the value of TraTotype
     */
    public String getTraTotype() {
        return (String)getAttributeInternal(TRATOTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraTotype.
     * @param value value to set the TraTotype
     */
    public void setTraTotype(String value) {
        setAttributeInternal(TRATOTYPE, value);
    }

    /**
     * Gets the attribute value for TraTortype, using the alias name TraTortype.
     * @return the value of TraTortype
     */
    public String getTraTortype() {
        return (String)getAttributeInternal(TRATORTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraTortype.
     * @param value value to set the TraTortype
     */
    public void setTraTortype(String value) {
        setAttributeInternal(TRATORTYPE, value);
    }

    /**
     * Gets the attribute value for TraTocode, using the alias name TraTocode.
     * @return the value of TraTocode
     */
    public String getTraTocode() {
        return (String)getAttributeInternal(TRATOCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraTocode.
     * @param value value to set the TraTocode
     */
    public void setTraTocode(String value) {
        setAttributeInternal(TRATOCODE, value);
    }

    /**
     * Gets the attribute value for TraPrinted, using the alias name TraPrinted.
     * @return the value of TraPrinted
     */
    public String getTraPrinted() {
        return (String)getAttributeInternal(TRAPRINTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraPrinted.
     * @param value value to set the TraPrinted
     */
    public void setTraPrinted(String value) {
        setAttributeInternal(TRAPRINTED, value);
    }

    /**
     * Gets the attribute value for TraSourcesystem, using the alias name TraSourcesystem.
     * @return the value of TraSourcesystem
     */
    public String getTraSourcesystem() {
        return (String)getAttributeInternal(TRASOURCESYSTEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraSourcesystem.
     * @param value value to set the TraSourcesystem
     */
    public void setTraSourcesystem(String value) {
        setAttributeInternal(TRASOURCESYSTEM, value);
    }

    /**
     * Gets the attribute value for TraSourcecode, using the alias name TraSourcecode.
     * @return the value of TraSourcecode
     */
    public String getTraSourcecode() {
        return (String)getAttributeInternal(TRASOURCECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraSourcecode.
     * @param value value to set the TraSourcecode
     */
    public void setTraSourcecode(String value) {
        setAttributeInternal(TRASOURCECODE, value);
    }

    /**
     * Gets the attribute value for TraInterface, using the alias name TraInterface.
     * @return the value of TraInterface
     */
    public Timestamp getTraInterface() {
        return (Timestamp)getAttributeInternal(TRAINTERFACE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraInterface.
     * @param value value to set the TraInterface
     */
    public void setTraInterface(Timestamp value) {
        setAttributeInternal(TRAINTERFACE, value);
    }

    /**
     * Gets the attribute value for TraAcd, using the alias name TraAcd.
     * @return the value of TraAcd
     */
    public Number getTraAcd() {
        return (Number)getAttributeInternal(TRAACD);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraAcd.
     * @param value value to set the TraAcd
     */
    public void setTraAcd(Number value) {
        setAttributeInternal(TRAACD, value);
    }

    /**
     * Gets the attribute value for TraOrg, using the alias name TraOrg.
     * @return the value of TraOrg
     */
    public String getTraOrg() {
        return (String)getAttributeInternal(TRAORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraOrg.
     * @param value value to set the TraOrg
     */
    public void setTraOrg(String value) {
        setAttributeInternal(TRAORG, value);
    }

    /**
     * Gets the attribute value for TraClassOrg, using the alias name TraClassOrg.
     * @return the value of TraClassOrg
     */
    public String getTraClassOrg() {
        return (String)getAttributeInternal(TRACLASSORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraClassOrg.
     * @param value value to set the TraClassOrg
     */
    public void setTraClassOrg(String value) {
        setAttributeInternal(TRACLASSORG, value);
    }

    /**
     * Gets the attribute value for TraTocodeOrg, using the alias name TraTocodeOrg.
     * @return the value of TraTocodeOrg
     */
    public String getTraTocodeOrg() {
        return (String)getAttributeInternal(TRATOCODEORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraTocodeOrg.
     * @param value value to set the TraTocodeOrg
     */
    public void setTraTocodeOrg(String value) {
        setAttributeInternal(TRATOCODEORG, value);
    }

    /**
     * Gets the attribute value for TraFromcodeOrg, using the alias name TraFromcodeOrg.
     * @return the value of TraFromcodeOrg
     */
    public String getTraFromcodeOrg() {
        return (String)getAttributeInternal(TRAFROMCODEORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraFromcodeOrg.
     * @param value value to set the TraFromcodeOrg
     */
    public void setTraFromcodeOrg(String value) {
        setAttributeInternal(TRAFROMCODEORG, value);
    }

    /**
     * Gets the attribute value for TraOrderOrg, using the alias name TraOrderOrg.
     * @return the value of TraOrderOrg
     */
    public String getTraOrderOrg() {
        return (String)getAttributeInternal(TRAORDERORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraOrderOrg.
     * @param value value to set the TraOrderOrg
     */
    public void setTraOrderOrg(String value) {
        setAttributeInternal(TRAORDERORG, value);
    }

    /**
     * Gets the attribute value for TraDckcode, using the alias name TraDckcode.
     * @return the value of TraDckcode
     */
    public String getTraDckcode() {
        return (String)getAttributeInternal(TRADCKCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraDckcode.
     * @param value value to set the TraDckcode
     */
    public void setTraDckcode(String value) {
        setAttributeInternal(TRADCKCODE, value);
    }

    /**
     * Gets the attribute value for TraDckline, using the alias name TraDckline.
     * @return the value of TraDckline
     */
    public Integer getTraDckline() {
        return (Integer)getAttributeInternal(TRADCKLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraDckline.
     * @param value value to set the TraDckline
     */
    public void setTraDckline(Integer value) {
        setAttributeInternal(TRADCKLINE, value);
    }

    /**
     * Gets the attribute value for TraBarcode, using the alias name TraBarcode.
     * @return the value of TraBarcode
     */
    public String getTraBarcode() {
        return (String)getAttributeInternal(TRABARCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraBarcode.
     * @param value value to set the TraBarcode
     */
    public void setTraBarcode(String value) {
        setAttributeInternal(TRABARCODE, value);
    }

    /**
     * Gets the attribute value for TraCodeTransient, using the alias name TraCodeTransient.
     * @return the value of TraCodeTransient
     */
    public Number getTraCodeTransient() {
        return (Number)getAttributeInternal(TRACODETRANSIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraCodeTransient.
     * @param value value to set the TraCodeTransient
     */
    public void setTraCodeTransient(Number value) {
        setAttributeInternal(TRACODETRANSIENT, value);
    }

    /**
     * Gets the attribute value for TraCode, using the alias name TraCode.
     * @return the value of TraCode
     */
    public String getTraCode() {
        return (String)getAttributeInternal(TRACODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TraCode.
     * @param value value to set the TraCode
     */
    public void setTraCode(String value) {
        setAttributeInternal(TRACODE, value);
    }

    /**
     * Gets the attribute value for ItsNopo, using the alias name ItsNopo.
     * @return the value of ItsNopo
     */
    public String getItsNopo() {
        return (String)getAttributeInternal(ITSNOPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItsNopo.
     * @param value value to set the ItsNopo
     */
    public void setItsNopo(String value) {
        setAttributeInternal(ITSNOPO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getR5translines() {
        return (RowIterator)getAttributeInternal(R5TRANSLINES);
    }


    /**
     * @return the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public R5ordersImpl getR5orders() {
        return (R5ordersImpl)getAttributeInternal(R5ORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity its.mnr.mp5.baseclass.ExtendedEntityImpl.
     */
    public void setR5orders(R5ordersImpl value) {
        setAttributeInternal(R5ORDERS, value);
    }

    /**
     * Uses the link TransactionsTranslineLink to return rows of Translines
     */
    public RowIterator getTranslines() {
        return (RowIterator)getAttributeInternal(TRANSLINES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> POTransactionExistence.
     */
    public RowSet getPOTransactionExistence() {
        return (RowSet)getAttributeInternal(POTRANSACTIONEXISTENCE);
    }

    /**
     * @param traAcd key constituent
     * @param traCode key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number traAcd, String traCode) {
        return new Key(new Object[]{traAcd, traCode});
    }


}
