package its.mnr.mp5.vo.parts;

import its.mnr.mp5.baseclass.ExtendedViewRowImpl;
import its.mnr.mp5.eo.local.R5binstockImpl;

import its.mnr.mp5.vo.parts.common.PartsBinstockViewRow;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Nov 25 13:58:55 PST 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartsBinstockViewRowImpl extends ExtendedViewRowImpl implements PartsBinstockViewRow {

    // Some constants
    public static final int ENTITY_R5BINSTOCK = 0;
    public static int NUMBER = Types.NUMERIC;
    public static int DATE = Types.DATE;
    public static int VARCHAR2 = Types.VARCHAR;
    
    protected Object callStoredFunction(int sqlReturnType, String stmt, Object[] bindVars) {
        CallableStatement st = null;
        try {
            // 1. Create a JDBC CallabledStatement
            st = getDBTransaction().createCallableStatement("begin ? := " + stmt + ";end;", 0);
            // 2. Register the first bind variable for the return value
            st.registerOutParameter(1, sqlReturnType);
            if (bindVars != null) {
                // 3. Loop over values for the bind variables passed in, if any
                for (int z = 0; z < bindVars.length; z++) {
                    // 4. Set the value of user-supplied bind vars in the stmt
                    st.setObject(z + 2, bindVars[z]);
                }
            }
            // 5. Set the value of user-supplied bind vars in the stmt
            st.executeUpdate();
            // 6. Return the value of the first bind variable
            return st.getObject(1);
        } catch (SQLException e) {
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    // 7. Close the statement
                    st.close();
                } catch (SQLException e) {
                }
            }
        }
    }
    
    public String BinTransfer(String pOBin, String pOLot, String pNBin, String pNLot, Number pNQty, String pPart, String pPartOrg, String pStore) {
       //System.out.println("Function BinTransfer");
        String ret = (String)callStoredFunction(VARCHAR2, "mnrpkg.BinTransfer(?,?,?,?,?,?,?,?)",
                                          new Object[] { pOBin, pOLot, pNBin, pNLot, pNQty, pPart, pPartOrg, pStore});
        
        return ret;
    }
    
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        BisBin {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisBin();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisBin((String)value);
            }
        }
        ,
        BisCreated {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisCreated();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisCreated((Timestamp)value);
            }
        }
        ,
        BisCreatedby {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisCreatedby();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisCreatedby((String)value);
            }
        }
        ,
        BisLot {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisLot();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisLot((String)value);
            }
        }
        ,
        BisPart {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisPart();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisPart((String)value);
            }
        }
        ,
        BisPartOrg {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisPartOrg();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisPartOrg((String)value);
            }
        }
        ,
        BisQty {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisQty();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisQty((Number)value);
            }
        }
        ,
        BisStore {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisStore();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisStore((String)value);
            }
        }
        ,
        BisUpdated {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisUpdated();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisUpdated((Timestamp)value);
            }
        }
        ,
        BisUpdatedby {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getBisUpdatedby();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setBisUpdatedby((String)value);
            }
        }
        ,
        tIsBinEmpty {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.gettIsBinEmpty();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.settIsBinEmpty((Boolean)value);
            }
        }
        ,
        tNewBin {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.gettNewBin();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.settNewBin((String)value);
            }
        }
        ,
        tNewLot {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.gettNewLot();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.settNewLot((String)value);
            }
        }
        ,
        tNewQty {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.gettNewQty();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.settNewQty((Number)value);
            }
        }
        ,
        tTransferLine {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.gettTransferLine();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.settTransferLine((Boolean)value);
            }
        }
        ,
        PartBinsView {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getPartBinsView();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        R5lotsView {
            public Object get(PartsBinstockViewRowImpl obj) {
                return obj.getR5lotsView();
            }

            public void put(PartsBinstockViewRowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(PartsBinstockViewRowImpl object);

        public abstract void put(PartsBinstockViewRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int BISBIN = AttributesEnum.BisBin.index();
    public static final int BISCREATED = AttributesEnum.BisCreated.index();
    public static final int BISCREATEDBY = AttributesEnum.BisCreatedby.index();
    public static final int BISLOT = AttributesEnum.BisLot.index();
    public static final int BISPART = AttributesEnum.BisPart.index();
    public static final int BISPARTORG = AttributesEnum.BisPartOrg.index();
    public static final int BISQTY = AttributesEnum.BisQty.index();
    public static final int BISSTORE = AttributesEnum.BisStore.index();
    public static final int BISUPDATED = AttributesEnum.BisUpdated.index();
    public static final int BISUPDATEDBY = AttributesEnum.BisUpdatedby.index();
    public static final int TISBINEMPTY = AttributesEnum.tIsBinEmpty.index();
    public static final int TNEWBIN = AttributesEnum.tNewBin.index();
    public static final int TNEWLOT = AttributesEnum.tNewLot.index();
    public static final int TNEWQTY = AttributesEnum.tNewQty.index();
    public static final int TTRANSFERLINE = AttributesEnum.tTransferLine.index();
    public static final int PARTBINSVIEW = AttributesEnum.PartBinsView.index();
    public static final int R5LOTSVIEW = AttributesEnum.R5lotsView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PartsBinstockViewRowImpl() {
    }

    /**
     * Gets R5binstock entity object.
     * @return the R5binstock
     */
    public R5binstockImpl getR5binstock() {
        return (R5binstockImpl)getEntity(ENTITY_R5BINSTOCK);
    }

    /**
     * Gets the attribute value for BIS_BIN using the alias name BisBin.
     * @return the BIS_BIN
     */
    public String getBisBin() {
        return (String) getAttributeInternal(BISBIN);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_BIN using the alias name BisBin.
     * @param value value to set the BIS_BIN
     */
    public void setBisBin(String value) {
        setAttributeInternal(BISBIN, value);
    }

    /**
     * Gets the attribute value for BIS_CREATED using the alias name BisCreated.
     * @return the BIS_CREATED
     */
    public Timestamp getBisCreated() {
        return (Timestamp) getAttributeInternal(BISCREATED);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_CREATED using the alias name BisCreated.
     * @param value value to set the BIS_CREATED
     */
    public void setBisCreated(Timestamp value) {
        setAttributeInternal(BISCREATED, value);
    }

    /**
     * Gets the attribute value for BIS_CREATEDBY using the alias name BisCreatedby.
     * @return the BIS_CREATEDBY
     */
    public String getBisCreatedby() {
        return (String) getAttributeInternal(BISCREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_CREATEDBY using the alias name BisCreatedby.
     * @param value value to set the BIS_CREATEDBY
     */
    public void setBisCreatedby(String value) {
        setAttributeInternal(BISCREATEDBY, value);
    }

    /**
     * Gets the attribute value for BIS_LOT using the alias name BisLot.
     * @return the BIS_LOT
     */
    public String getBisLot() {
        return (String) getAttributeInternal(BISLOT);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_LOT using the alias name BisLot.
     * @param value value to set the BIS_LOT
     */
    public void setBisLot(String value) {
        setAttributeInternal(BISLOT, value);
    }

    /**
     * Gets the attribute value for BIS_PART using the alias name BisPart.
     * @return the BIS_PART
     */
    public String getBisPart() {
        return (String) getAttributeInternal(BISPART);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_PART using the alias name BisPart.
     * @param value value to set the BIS_PART
     */
    public void setBisPart(String value) {
        setAttributeInternal(BISPART, value);
    }

    /**
     * Gets the attribute value for BIS_PART_ORG using the alias name BisPartOrg.
     * @return the BIS_PART_ORG
     */
    public String getBisPartOrg() {
        return (String) getAttributeInternal(BISPARTORG);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_PART_ORG using the alias name BisPartOrg.
     * @param value value to set the BIS_PART_ORG
     */
    public void setBisPartOrg(String value) {
        setAttributeInternal(BISPARTORG, value);
    }

    /**
     * Gets the attribute value for BIS_QTY using the alias name BisQty.
     * @return the BIS_QTY
     */
    public Number getBisQty() {
        return (Number) getAttributeInternal(BISQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_QTY using the alias name BisQty.
     * @param value value to set the BIS_QTY
     */
    public void setBisQty(Number value) {
        setAttributeInternal(BISQTY, value);
    }

    /**
     * Gets the attribute value for BIS_STORE using the alias name BisStore.
     * @return the BIS_STORE
     */
    public String getBisStore() {
        return (String) getAttributeInternal(BISSTORE);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_STORE using the alias name BisStore.
     * @param value value to set the BIS_STORE
     */
    public void setBisStore(String value) {
        setAttributeInternal(BISSTORE, value);
    }

    /**
     * Gets the attribute value for BIS_UPDATED using the alias name BisUpdated.
     * @return the BIS_UPDATED
     */
    public Timestamp getBisUpdated() {
        return (Timestamp) getAttributeInternal(BISUPDATED);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_UPDATED using the alias name BisUpdated.
     * @param value value to set the BIS_UPDATED
     */
    public void setBisUpdated(Timestamp value) {
        setAttributeInternal(BISUPDATED, value);
    }

    /**
     * Gets the attribute value for BIS_UPDATEDBY using the alias name BisUpdatedby.
     * @return the BIS_UPDATEDBY
     */
    public String getBisUpdatedby() {
        return (String) getAttributeInternal(BISUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for BIS_UPDATEDBY using the alias name BisUpdatedby.
     * @param value value to set the BIS_UPDATEDBY
     */
    public void setBisUpdatedby(String value) {
        setAttributeInternal(BISUPDATEDBY, value);
    }


    /**
     * Gets the attribute value for the calculated attribute tIsBinEmpty.
     * @return the tIsBinEmpty
     */
    public Boolean gettIsBinEmpty() {
        return (Boolean) getAttributeInternal(TISBINEMPTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute tIsBinEmpty.
     * @param value value to set the  tIsBinEmpty
     */
    public void settIsBinEmpty(Boolean value) {
        setAttributeInternal(TISBINEMPTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute tNewBin.
     * @return the tNewBin
     */
    public String gettNewBin() {
        return (String) getAttributeInternal(TNEWBIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute tNewBin.
     * @param value value to set the  tNewBin
     */
    public void settNewBin(String value) {
        setAttributeInternal(TNEWBIN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute tNewLot.
     * @return the tNewLot
     */
    public String gettNewLot() {
        return (String) getAttributeInternal(TNEWLOT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute tNewLot.
     * @param value value to set the  tNewLot
     */
    public void settNewLot(String value) {
        setAttributeInternal(TNEWLOT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute tNewQty.
     * @return the tNewQty
     */
    public Number gettNewQty() {
        return (Number) getAttributeInternal(TNEWQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute tNewQty.
     * @param value value to set the  tNewQty
     */
    public void settNewQty(Number value) {
        setAttributeInternal(TNEWQTY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute tTransferLine.
     * @return the tTransferLine
     */
    public Boolean gettTransferLine() {
        return (Boolean) getAttributeInternal(TTRANSFERLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute tTransferLine.
     * @param value value to set the  tTransferLine
     */
    public void settTransferLine(Boolean value) {
        setAttributeInternal(TTRANSFERLINE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartBinsView.
     */
    public RowSet getPartBinsView() {
        return (RowSet)getAttributeInternal(PARTBINSVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> R5lotsView.
     */
    public RowSet getR5lotsView() {
        return (RowSet)getAttributeInternal(R5LOTSVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
